  nginx_manager:
    image: jc21/nginx-proxy-manager:2
    restart: always
    container_name: nginx_manager
    ports:
      # Public HTTP Port:
      - "80:80"
      # Public HTTPS Port:
      - "443:443"
      # Admin Web Port:
      - "81:81"
    environment:
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=npm
      - DB_MYSQL_NAME=npm
      - DB_MYSQL_HOST=nginx_manager_db
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      # Make sure this config.json file exists as per instructions above:
      #- ./volumes/nginx-manager/config.json:/app/config/production.json
      - ./volumes/nginx-manager/data:/data
      - ./volumes/nginx-manager/letsencrypt:/etc/letsencrypt
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - nginx_manager_db

  nginx_manager_db:
    image: 'jsurf/rpi-mariadb:latest'
    container_name: db
    environment:
     -  MYSQL_ROOT_PASSWORD=npm
     -  MYSQL_DATABASE=npm
     -  MYSQL_USER=npm
     -  MYSQL_PASSWORD=npm
    volumes:
      - ./volumes/nginx-manager/mysql:/var/lib/mysql:rw
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"


