#!/bin/bash

# Mini web server for IOTSTACK
# based on :

# --------------------------------
# Totally Simple Web Server (TSWS)
# --------------------------------
#
#  (c) 2015 Dave Fletcher
#  All Rights Reserved
#
#  This is free and unencumbered software released into the public domain.
#
#  Anyone is free to copy, modify, publish, use, compile, sell, or
#  distribute this software, either in source code form or as a compiled
#  binary, for any purpose, commercial or non-commercial, and by any
#  means.
#
#  In jurisdictions that recognize copyright laws, the author or authors
#  of this software dedicate any and all copyright interest in the
#  software to the public domain. We make this dedication for the benefit
#  of the public at large and to the detriment of our heirs and
#  successors. We intend this dedication to be an overt act of
#  relinquishment in perpetuity of all present and future rights to this
#  software under copyright law.

#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#  IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
#  OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
#  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#  OTHER DEALINGS IN THE SOFTWARE.
#
#  For more information, please refer to <http://unlicense.org>
#

# All informative console log messages are piped to here so e.g. it could be
# quieted by setting TSWS_LOG=/dev/null or alternatively logged to a file.
# The default is $(tty) which prints logs to console. TSWS_LOG may be set
# in the environment before running the script or changed before calling the
# tsws function.
[ -z "${TSWS_LOG}" ] && declare TSWS_LOG="$(tty)"

# -----------------------------------------------------------------------------
# tsws [host [, port]]
# -----------------------------------------------------------------------------
#
# Start the Totally Simple Web Server. Note that the `tsws` script that this
# function lives in has the same interface as the function: tsws HOST PORT and
# the script itself can be used in the same way as "Example usage" below.
#
# ---------
# Arguments
# ---------
#
#    - host: IP address (or hostname) to listen on. Optional. If not
#            supplied the default value is 127.0.0.1
#
#    - port: Port to listen on. Optional. If not supplied the default
#            value is 18080
#
# -------------
# Example usage
# -------------
#
#  # Launch the webserver. This version will not return, it will loop forever.
#  tsws localhost 8080
#
#  # Alternatively, launch the webserver and return immediately.
#  tsws localhost 8080 &
#  # Catch the PID so we can wait or kill later.
#  declare tsws_pid=$!
#  # Launch a browser. Don't detach, wait for exit.
#  firefox "http://localhost:8080"
#  # User closed the browser, we're done, stop the server.
#  kill ${tsws_pid}
#
# -------------------
# Theory of operation
# -------------------
#
# The nc program opens a network port and begins listening. When an inbound
# connection is made, the STDOUT of nc is pushed to a FIFO pipe. The
# _tsws_response function runs concurrently and waits for input from the FIFO
# pipe. When _tsws_response finds an HTTP request there, it processes and
# returns a well-formed HTTP response back to nc STDIN. nc sends this
# response back to the requesting client.
#
# --------------------------------------------------------------------------
#
#                                        +----+ (1)
#       Browser <===> The Internet <===> | nc | ---> FIFO pipe ---+
#                                        +----+                   |
#                                       (0) ^                     |
#                                           |                     |
#                                           +-- _tsws_response <--+
#
#    - 1: STDOUT of `nc` process which carries HTTP requests.
#    - 0: STDIN of `nc` process which carries HTTP responses.
#    - _tsws_response: handler function reads requests, produces responses.
#
# --------------------------------------------------------------------------
#                                               Diagram: Theory of operation
#
# ------------
# Requirements
# ------------
#
#   - Bash (obviously).
#
#   - Netcat (nc) handles the network listen call for us and binds stdin and
#     stdout of the nc process to connected clients.
#
#   - mkfifo: A FIFO pipe connects the output of nc to our _tsws_response
#     function which processes requests and sends responses back through stdin
#     of nc to browser client.
#
#   - wc -c: For calculating Content-Length.
#
#   - cat, tee: For pushing files and HTTP data through pipes.
#
#   - date, uname: Just to show some dynamic content in www_index. Also date
#     is used in logging.
#
#   - base64: Demonstrates script-embedded binary files.
#
# ---------------------
# Known issues and bugs
# ---------------------
#
#   - This setup almost certainly has issues with concurrency. It is useful for
#     a single local user or demonstration purposes, but please do not use it
#     as a production web server connected to the internet.
#
#   - All HTTP caching is ignored keep things simple.
#
#   - Cygwin doesn't work so great. Particularly, some requests just fail
#     inexplicably with nc never supplying a request or supplying a massively
#     delayed one.
#
#   - It is easily confused, especially if multiple browsers or tabs are
#     pointed to it at the same time. Requests and responses might get dropped
#     (still not quite sure why on that) and the order can get out of whack,
#     sending the wrong file for a request.
#
#   - Iterative development is awkward. Altering functions while bash is
#     running confuses it, and the server must be restarted to see changes.
#
#   - Parsing CGI variables off URLs is weak. TODO find a decent way to do it
#     that doesn't baloon the example code.
#
#   - Killing the server with Ctrl-C is awkward? Needs testing.
#
function tsws {

  local -r host="${1:-127.0.0.1}"
  local -r port="${2:-18080}"
  local -r fifo="$(mktemp -u)"
  
  # Initialize the FIFO pipe.
  mkfifo -m 600 "${fifo}"
  trap "rm ${fifo}" EXIT INT TERM HUP # Auto-cleanup at exit.

  # Connect _tsws_response to STDIN. Connect STDOUT to FIFO pipe. Then listen
  # on ${host}:${port}. nc -l is "listen" and -k is "listen forever".
  printf $'\ntsws HTTP/1.1' >"${TSWS_LOG}"
  printf $' started %s' "$(date)" >"${TSWS_LOG}"
  printf $' on %s:%s\n\n' "${host}" "${port}" >"${TSWS_LOG}"
  nc -kl "${host}" ${port} \
    0< <(_tsws_response "${fifo}") \
    1> >(while : ; do cat - > "${fifo}"; done) \
    2>"${TSWS_LOG}" # Loop ^^ keeps pipe open.
    # Send ^^ nc errors (2>) to the log.
}

# -----------------------------------------------------------------------------
# _tsws_response(fifo)
# -----------------------------------------------------------------------------
#
# Internal workhorse function for handling requests and responses for tsws.
# Do not call it directly.
#
function _tsws_response {
  local method path httpvers callback content_type status msg obf clen
  method=""
  while : ; do # Run forever.
    while read -r line; do
      line="$(sed 's/\r//g' <<< "${line}")" # Replace CRLF with \n
      if [ -n "${line}" ]; then
        # ${line} is not empty, it is either a "Request-Line" or a header
        # line. If we have no 'method' yet we assume it is a Request-Line.
        # http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html
        if [ -z "${method}" ]; then
          read -r method path httpvers <<< "${line}"
          continue
        fi
        # TODO: if we cared about any of the request headers, here is the
        # place to read them by parsing ${line}.
      else
        # ${line} is empty, so we received two consecutive CRLF.
        # Process the request.
        #
        # Currently all "files" served up by the server are functions in this
        # script that return content. This shows how dynamic content can be
        # served and keeps this example all in one single file. It should be
        # easy to adapt this to also read real files from disk Hint: obf below
        # and use `file` to get content_type.
        unset cgi_get
        local -A cgi_get
        IFS='?#' read path query fragment <<< "${path}"
        while read -d $'&' namevaluepair || [ -n "${namevaluepair}" ]; do
          # Note this method of parsing CGI variables is currently really weak
          # and ignores & that are escaped as &amp;
          IFS=$'=' read name value <<< "${namevaluepair}"
          # The worst possible unescaping, replace + with space.
          value="$(sed 's/\+/ /g' <<< "${value}")"
          cgi_get["${name}"]="${value}"
        done <<< "${query}"
        callback="www$(sed -e 's/\//_/g' -e 's/\./_/g' <<< "${path}")"
        [ "${callback}" = "www_" ] && callback="www_index"
        content_type="${callback}_Content_Type"
        content_type="${!content_type}"
        [ -z "${content_type}" ] && content_type="text/plain"
        obf="$(mktemp -u)"
        case "${method:?}" in
          GET)
            if local -f  "${callback}" > /dev/null; then
              # ${callback} is a function we declared.
              status=200; msg="OK"
              ${callback} > "${obf}"
            else
              # ${callback} is not defined.
              status=404; msg="Not Found"
              printf $'Not found: %s.' "${path}" > "${obf}"
            fi
          ;;
          *)
            # Currently we only handle GET requests.
            status=500; msg="Internal Server Error"
            printf $'Server Error: unknown method %s.' "${method}" > "${obf}"
          ;;
        esac
        clen=$(cat "${obf}"|wc -c)
        # Show request in term.
        printf $'%s %s' "${method}" "${path} $(date); " >"${TSWS_LOG}"
        # Output headers, tee shows the response headers in term.
        printf $'HTTP/1.1 %s %s\r\n' "${status:?}" "${msg:?}" | tee "${TSWS_LOG}"
        printf $'Content-Length: %s\r\n' "${clen}" | tee "${TSWS_LOG}"
        printf $'Content-Type: %s\r\n' "${content_type}" | tee "${TSWS_LOG}"
        printf $'Connection: close\r\n' | tee "${TSWS_LOG}"
        printf $'\r\n' | tee "${TSWS_LOG}"
        # Output the response data.
        cat "${obf}"
        # This is meant to clean up a temporary file so if you alter the code
        # to handle real files don't let this accidentally delete it!
        rm "${obf}"
        # Reset for the next loop iteration.
        method=""
      fi
    done < "$1"
  done
}


# +---------------------------------------------------------------------------+
# |                                  WWW FILES                                |
# +---------------------------------------------------------------------------+

declare www_index_Content_Type="text/html; charset=utf-8"
function www_index {
# Note here we use <<EOF *without* the backslash, we want Bash to interpret
# variables and subcommands in this text.
cat <<EOF
<!DOCTYPE html>
<html>
  <head>
    <title>TSWS, A Totally Simple Web Server</title>
    <!--script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script-->
    <script type="text/javascript" src="/site.js"></script>
    <style type="text/css">@import url("/style.css");</style>
  </head>
  <body>
    <h1>IOTSTCK, absolutely mini web server</h1>
    <img class="graphic" src="/graphic.png" />
    <b>Repository is</b> <a href=https://github.com/cayetano/IOTstack> GitHab </a><br>
    <p><em>A web server in <a href="https://www.gnu.org/software/bash/">Bash</a> and <a href="http://nc110.sourceforge.net/">Netcat</a>.</em></p>
    <table>
      <tr>
        <td class="th">Generated by</td>
        <td>$(uname -a)</td>
      </tr>
      <tr>
        <td class="th">On</td>
        <td>$(date)</td>
      </tr>
      <tr>
        <td class="th">Version</td>
        <td>${httpvers}</td>
      </tr>
      <tr>
        <td class="th">Status</td>
        <td>${status} ${msg}</td>
      </tr>
EOF
	cat $filepath

cat <<EOF
    </table>
    <a href="https://github.com/cayetano/IOTstack" title="Fork me on GitHub"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"></a>
  </body>
</html>
EOF
}

declare www_style_css_Content_Type="text/css"
function www_style_css {
# Use <<\EOF for raw output with no Bash interpretation of the value.
cat <<\EOF

@import url(//fonts.googleapis.com/css?family=Lato:400,700,400italic);

BODY {
  font-family: 'Lato', sans-serif;
  margin: 10%;
}

A, A:visited {
  color: #060;
  text-decoration: none;
}

A:active, A:hover {
  color: #393;
  text-decoration: underline;
}

TABLE {
  font-size: smaller;
  border: 0;
}

TD {
  vertical-align: top;
}

.th {
  font-weight: bold;
  white-space: nowrap;
  padding-right: 1em;
  text-align: right;
}

.graphic {
  float: right;
  margin-left: 2em;
  position: relative;
  top: -2em;
  z-index: -1;
}

EOF
}

declare www_site_js_Content_Type="text/javascript"
function www_site_js {
# Use <<\EOF for raw output with no Bash interpretation of the value.
cat <<\EOF
/*(function ($) {
  $(document).ready(function() { alert('hi!'); });
}(jQuery));*/
EOF
}

declare www_graphic_png_Content_Type="image/png"
function www_graphic_png {
# Note: The base64 here is is just to show how a binary file could be
# returned from a Bash function. As a different type of example, this could
# be the output of ImageMagick instead of a hard-coded base64 jpeg.
#
# Use <<\EOF for raw output with no Bash interpretation of the value.
base64 -d <<\EOF
iVBORw0KGgoAAAANSUhEUgAAAfQAAAHlCAYAAAADXA60AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAhGVYSWZNTQAqAAAACAAFARIAAwAAAAEA
AQAAARoABQAAAAEAAABKARsABQAAAAEAAABSASgAAwAAAAEAAgAAh2kABAAAAAEAAABaAAAAAAAAAFoA
AAABAAAAWgAAAAEAA6ABAAMAAAABAAEAAKACAAQAAAABAAAB9KADAAQAAAABAAAB5QAAAAAjrP+NAAAA
CXBIWXMAAA3XAAAN1wFCKJt4AAACamlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4
bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNi4wLjAiPgogICA8cmRmOlJE
RiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgog
ICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJo
dHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDov
L25zLmFkb2JlLmNvbS9leGlmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZm
Ok9yaWVudGF0aW9uPgogICAgICAgICA8dGlmZjpSZXNvbHV0aW9uVW5pdD4yPC90aWZmOlJlc29sdXRp
b25Vbml0PgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MTU1MTwvZXhpZjpQaXhlbFlEaW1l
bnNpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4xNjAwPC9leGlmOlBpeGVsWERpbWVu
c2lvbj4KICAgICAgICAgPGV4aWY6Q29sb3JTcGFjZT4xPC9leGlmOkNvbG9yU3BhY2U+CiAgICAgIDwv
cmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgpy8d2BAABAAElEQVR4Aex9
CYAkZXn2V1Xdc3RVL4eCt6jBC4wBxeWGRQW8EXRnZhFQo4gHaFTARFRmBU88Ip7ggXLtTC+HKKggygK7
HLsak/yCiWcSTaISObarumemu6r+5/mqqqd756qemZ7p4/1gp6+vqquer7qe732/931epaQJAoKAICAI
CAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgCgoAgIAgIAoKA
ICAICAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgCgoAgIAgI
AoKAICAICAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgCgoAg
IAgIAoKAICAICAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgC
goAgIAgIAoKAICAICAKCgCAgCAgCgoAgIAgIAoKAICAICAKCgCAgCAgCHY9AIbQ6/hzkBAQBQUAQEAQE
gZ5FIAwNpfgPLSL16HnPAiInLggIAoKAICAIdBoCo6GZHHK2UFqrn5PgNcknn8ijICAICAKCgCAgCLQv
AnUudmvc+7J1Yxia48V36gPmZ0Lq7Tt2cmSCgCAgCAgCgoBGoIHM3U3WTWFojbu+9V2SuvdB3YfWe50F
L8gJAoKAICAICAKCQDshMBpmksMBid9ofU+T+ZQm9HG3SnLPjLsf131opQupJ3DJoyDQ8QjUfvwdfyZy
AoJAryNwyU+y6gyjom4LM9afvB8qx16nit4UYOmLoQmVV6qGjv0+kPpg1TDehfdDuN9NZRhBr8Mn5y8I
dDoCEvHa6SMoxy8IEAGQuDrGqKrvhjmr5N0GMl+r3BLIPEzIPMIJIXH4z1d5O6N2ul/zR/Kn6w/oph8y
/KiT/BUEBIFORKAWBduJBy/HLAgIAkDgkjCryfyqh/cwS949yiaZ0zLfhcwJVqg4ibdguVfUGufNcMVf
ybc1mdetvev35I8gIAh0FAJioXfUcMnBCgK7IEAyp5u94D7WCo07VS63ryo1uNl32aDhZQWWelYVS9f6
w/Zr9SdiqTcAJC8EgU5CQCz0ThotOVZBoB6Bn8Rkfn35KZYydqhBkLkHy3t6zby+92zPSeZTKp97DSz1
m3QHut1Hb5PYmtnQkvcEgTZHQCz0Nh8gOTxBYFYECnCnDxlT6uqdz7Is807Vbz9aTc6yZj7rxjPenMKa
ex/c9D/2h+xjdYBcsiY/o6u8IQgIAu2KgBB6u46MHJcgMBcCtMwPMirZMfdvAiO8Q/Xl1qipMi3z7Fyb
pHg/JvXSNt/IvVBPFoTUU8AmXQSB9kFAXO7tMxZyJILAwgjQMgeZq02PHBwY6m6VHVwOMuf30kKfUnbu
cCvwtjFaXgfaMRVOmiAgCHQEAmKhd8QwyUEKAkCgcB/c7PtPZcbLR4UquFVlsllVnaoqZWDNO1wuiEDq
dp/hev9aNaeOUkN7PqKj6Bl4J00QEATaGgEh9LYeHjk4QSBGIHazZ8bc46DvdrOyYDj7FZC5akUA25TK
gdRL3r9X/eAIdfKa/xNSlytREGh/BITQ23+M5Ah7HYGYzK2xnSeAyL+NoDWQebVVZJ6gPaUGEShX9n7n
Z4zD1Wvs/1XxcSQd5FEQEATaCwFZQ2+v8ZCjEQQaEWBgGtbMrUJpWPUNflt/6Fep6NYKy7z+u0HmiJof
tJ9q+Wq7KpSfrNfu6faXJggIAm2JgBB6Ww6LHJQgAATiKHNY5m9Uff1jWC9XKvBJ5tbK4IMAPJJ6f+6J
VuiD1Cf25Rq+XstfmQOQbxEEBIEmEBBCbwIs6SoIrAgCURU0rc1uFry3qcH8N9RkGXFv4QqSeXKmIPUJ
iNX0Dz7GCqvb1dXF/YXUE2zkURBoLwRkDb29xkOOptcRIJlvVia11c1x971Gzv4UpFwZws5/qzkBr8Dl
n1VTJdcMzKMqG+yfJVH3vT5kcv6CQLsgsJo3iHbBQI5DEGgPBDSZb47JvPiBmMxZ1nS1yZz4gMwnKio7
4EDM5q7s2COHiKXeHpeNHIUgkCAgFnqChDwKAquJwChqkp/PWmhGmCl4F4Z27jwIvdDFzkl3O/1OqyrT
l2H+Oyqxvqg6nL9DLPXVvHDkuwWBaQTa6UYxfVTyTBDoJQRI5qO0wkHm4+5nQsd+d5uSeTIqVaTPZVRQ
CY1AvaQ64tzS9SlthYKl7l9vqP20tyTBYeHH9ei/cZdu+63CBO3+LSnv9et2Odi6l0fXPW+Xp+uUz0lw
uxzOah9HykFe7cOU7xcEuhQBEsXQEC1xZRW8Lykn9zbUKmeOOSPZ2/f3aaiqMjMZBOoh8j54Fcqvfrdr
xWe4FCKkwUu0PZuMT21cWp3LWvsieSIICAK7IFBXexxkfhnI/A0oZ1oBjYMo25jMeRohjjHwq8owM5Cg
/Q7y5Nf7Q8Y1XUfqHCODAYqldxpG8HJMYEp43a/nWiE8K/OmENJwNLA9/mMkBHuH+A+yQPg3R9PbsF+A
/j4eGyd19RMLEplSkOTFrMrAzuNNazvma8XJSBjgM04S6xoPJkAPSPpGhMjPeFzT38lJmz5yfg26hpT/
5YnolzwyLLsY/HIcVRAEhlGN92qY3Fafg34H24b8fn1EOFagEMTHg+cGPuM7Sn8fnkWvcf68vgIU9MUx
+aGyTDxD2qZp8f0KDiXwTXUvvv6/43OI9q8PsDf/CKH35rjLWa82Ag1k7o6BzIdhmXcGmSfYhRC9CXGD
DQNLZfs3o6b6qf6wcaViQZczno8bdve4QhEvMKQebR+uijh5+k7SUsds/RopOkFz8Y/Lvb8mjiQ5PT5S
wFA/4o+eajSxH3ad9TT4Zv2X8Dn/+aD/vKnMv3jn4Nmn1KU/JZf1fL0BIXRcBdIEgRVFYPS2DNLStIUC
y/wGkPmr1E5N5tnazWtFD2hJX2bBOvJVZdJCTfYrIIIz4I+s+VokiqMtvuR2vKQvWbWN18cmqRFU1CMw
YKcmJnAsct9cjQGJyD3h/aqasPsxi8jpQ3nG8zv7OlsmPOXCXCYgZTeCQCoEajXGQwMW7c0oV3os3OxT
ME86WVIVpA7ynvQslct/1SwUB4JjjC+oUVjw5+P9ejdxKpDaqFNy7CGIw9QCfSwnu0JKfW2EQzscSiNl
BzTpTWUMxosA7XCEq34MQuirPgRyAD2DQELml4RZa3fvVuU4RykXZK6gxtbxDWvNXGAte7CZnM9DFGcg
GDY+pfbD+yGWRxNi7NDzBJf0cbVYWtsgEFnqYRBZ6Le3zXGt6oEwYkGaICAItBqBGpn/T87avbQVNcdB
5l6XkHkNPN5PQijbBYZtX4R8+vOoeIf3sAS9mFXV2n5X9wmOHSeGCYsQ+uoOxC7fjuEIwxABimjNphPu
sqtueSmE3i0jKefRvgjAIlfHYM28EO5m7rHmbpXLrVUeybyj3exz4Y17Cownz/PDXO7CzHjxAljnAXKx
DbjgO+x+E09CKMVLQhc+n2vMV+99w+gC79bywScu9+XDUvYkCMxEgGR+BtJ9rt75aDP0tkLO9ZmwYLuV
zOPz18QdalJ3nA9ALGegOmycE1npFNEBwXdSe+inptr9WZGFzmStyNnbSWfQvceaWOjde4ZNnZkQelNw
SWdBoAkEfgIyRy1ztemBx1umuZW1xbufzGv4kPZMLCtUoXx3NqL5B3zDOAvvMc8YsUwdROp7PB/L565Y
6LWhbZMn9JgYZmyhb26Tg1rdw+gwF9jqgiXfLgikRqBwX58m82vL+1jm4HY1oMmcebK95CKkNWsh8K+C
1LwzrbHiVzV+JHPm4XdUg1QKm1jnbTZq8Rr6+vWyIIKREUJvs8tTDqcLECCZD+0/pQoT+1pVn2T+BER/
UzSGKU+91bSLGulrVMBb47zZGnMv1wAwWI6yt53QHIxcGIDKhTPaarii4YgmyBvb6shW7WCE0FcNevni
rkQgIfOri/tbYWU7aojvrSZ6lMyTAU5IneI5a+xTkX8/rj+ihn07W+r1/A110+R05LGNEAhVFOXeRoe0
mocihL6a6Mt3dxcCCZmPec+zLPMe1ZfbQ02V6WbvPct815GNgsmyWt42bw9ZheK3dRdtqbe5+/1P/4Gl
A+HzXYd0VV9zODjhMuMo9/PFfcLxEEInCtIEgaUiEJN5dqx0iGWobSrb5wiZzwoqSB1iOrZzAiz17+se
JHWqyrVz6+Q8+nbGdanHFiLwVFoNASH0GhTyRBBYJAIxmWcKxaMDM7wT1ccGoG1OrXa52cwKKZTxKKrj
2C8Bqf9I56ePIk+f4jvSBIFUCEQeEzh+OiMOI9U5Lb2TEPrSMZQ99DICTE1DABxyrY+HEbdFWagRXp0i
mQs5zX9dgNRhqTv2C61nl27XZVcpviOkPj9q8mmEAD0mOsYhXq7pcGnh5RpWIfTlQlL203sIUDQGeebW
pp2vCk3rBwqlwZVfETJPfSXElrqdOwLa9lsRIDeoFfWIqzRBYEEENKPXWegdLC+84Lmm6yCEng4n6SUI
NCIQK8BZm0vrVd/ADfrDoIra4GKZNwK14Ks+LYNr22uhpHeXuiHMa2U91lSXJgjMhwCK5ZghlmkoVCRN
IyBAyIUgCDSLAMkGcq5WwT1VZfoKyodRHvgsQlJnLTS7057ur0kdsrgHZCa8e1ThkT3VGQdVtBu+p2GR
k0+BgKUujX939WmGKTbsxi5C6N04qnJOLUIALj2u8YJsoHr2FtVvX66mJljySch86Yj3URY3zNn7WaF5
r7quuLe21BmjIE0QmA0BWOjgcEv1/YdMpGN8hNBnu1DkPUFgBgIg89EtFtd4zbHiWSrnXALBGObCotBI
m+dRzziXtn0DpI5AuUEHCnvmdlUoPUHL58qaetsO2KodGHUNdFQcotwf/RThsXggBIhVuyLlizsGAUbU
FqDZMHoMyNw9x7CdiyHlSgdfgNuK/IaWdSARKFcGqffn9rHCYLu6vvwUbakX8L40QWBXBKjgV35AfoMx
LgLErheIvBYE6hEgmbOWN8RPUNv7g4ZjfxKuYZb/JKHL76ceq+V73qflcvvtx1tT0MK/ZuLpwH9Kift9
+RDumj3hZ1gUGb9kOOWGlCAhj4LArgiMInqWZI763Zlx7yOh43yYNb7jbvLb2RWvZXvNuRJEeSah/d43
uJflV7b3jRWfo93vq2ap6ziJZTtD2dESEWAWOoNRFbTc85b8FmM4BYglXleyeZciQDIfxU2DZD7mfjp0
cu9XXol3EP5m5HezMsOe1fK5fbndfUPdnb3GO1Bb6itN6vZTKEu2mwromGHMhLRVRoCT6kCtGcCD8Vs1
tOcj+ngi8bhVPrTV/Xq5Ma0u/vLt7YiAJnPU7FZGaI0Xvxjm7ffAMq8imp3RtHLbWNkxA6lPVFR2wAn8
8K7sNaWDV8z9TvUxLrkMGWWc8rdVDsv4JtWDlDYNVxYG+TaNQKgqSBW1VM7Oqofcq/yB0vHR+xgn/F57
HSUh9F6/AuT8GxFgOU9Y5XwTOuNfV3nn7dAdr8BWFzJvRGoFXyF1rTLFG/lA4AdbM+Plo1ba/e4P509H
UZk3geAn1aANUseafhRHsYI49PBXGXoSFag8iLw69UdVdtf7I/lT1Al7FXUtAJF+1ReHWBs9/BuRU98F
AZI5K3+hQTTmKuiMn6zLfSrmQstPZRe0VuNlFYVvMpDXDY0wc1x1eOBWHSgH+d3WHgysP13+FRO9wiP7
WqF1FYhlLa4NWoSc/EkedOsGgBhXkfWQVSGgnixf6lenzlGnPGonpIItdX+0LNa6r++sPctdqrPGS462
VQjUk/lY8Vq1xjlJ7YRlbkLKVee8tuqLZb9NIlDVBXB4cw/DV/hD9k0rQ+o4yqTePZ4i4+EjYXbg/Xqi
V5ngJBDeTrp8A7p+k1MiGfFF8sj3+Ryt/u3EXczHhhb3nd4hPo33xe/S/ePXDdvFLxIXdP1+9Xb8vP4A
+DrZT/LI92Zrs3y+61sN35Hso75T8pyPbHMcCyZQBvLM7UEVFr37IPN6ZnVDfoveIpZe1s/lTw2BXS+g
2gfyRBDoGQRYi5vlO9HgZr8R1tfLdc1uJbnPbXoN+Mq0LGWAQ0P/Nf763HVaJhZyvC0/3rqJH0j9GMz1
vgnr8clwA4OWZAVz+fAH1xPPyuQUAhk+GgznN+p9U6nxdnhF4mWx5fu+7tiTEHp3jKOcxWIRSMgcwU9W
wbsFbvYXaze7IbXMFwvpCm3n44ZvwQXPm/7J/rCzSWmNfWjAt7oxUO5SeG44gbg+3D0z4R6AKiEV2Jly
P10u7KnqGhjZquH/Xo3s/hu9W5I5S+xKmxMBuQDnhEY+6HoEkhsEBEus33o/UrZ9JALgGOwkqmSdMfgg
dbhks0hfmiq/AaT+rRWz1IlPcv10Blade5TEeZ3iWCcu+s49lxYfuRB6iwGW3bcpAsnNGDW4rbC0Rdm5
tbqMp5B5mw7YHIdFLX0DvtmBHAKmSmdgTf3SiGhBACuRxkRrfQuC4m7fMvsBvmKdoX5Ly/1+fL7f7H1W
7V0e0yLa0/aLiPWnC22LDs94/jQJ347++8Hyvn9LOt45ep0S9/pCGDd+ng7Yxm3klSDQ2QgkATVX/mWN
me2/3bDtA4TMO3hISeomSHPANsJS+Z3BSO7zSGXKqPPFqmurUeXkZyMKHJ2/TqztFg0MRRKkCQK9g0BC
5t/a+ahMxtiKcp3PEjLv8OFngRySetlTmJxdjAI6A8GIcZHaD2lNIcLhV9NVu6n0JGWZ/bDhA1WZaC8D
KttfxZQHUi11x5UdaHydXBrJ+3xEJKLqR+1SSC0pP0AqISZTRbyXySP1AKJt2d3w+BA01v1A7f1oH+fu
q+0QhDG0vkNVjWKnJPfVHJfkvLrssb0usC4DV06nzRBIyLzgPtYKwm0ogfo0XdlLotnbbKAWfTggEjTb
NkOv9MFg2L5Qi46cD+JZSfJIyAqP5mbvp4aROVAFVarNtVu+eoSXBq2pP/F2XNMOYpc6yBocH+FM3Xu9
3s0ARfwzpiAc4KHHlGEaN1fvz43qrJIEp6a+WjrPh4BY6POhI591DwI6hxjqXoUHn2yFaitqbj8JFp0E
wHXPCPNMmDcWwOPioyreBZmx4kB1xPgAzEHo8sMiXJ1Upz7V16/URHUAUfntZ0At6ojqN4pT9RoKnsWf
8z39Po1xPDfhSOlXB1nP9g7zw/BFmvyF1Jf1FyiEvqxwys7aEgGW3TwIZD728F9ZQWYbpDsfo8tzSgBc
Ww7XEg+KDBMiW8EP8855mXG3vzpsnIO3QOgkdu32XeJXNLV5oIu6GHA7qwBLANi2ng/n21Vs+zb0T7af
63HX/SX96t9P3uMj/7WuRXuPvo9/fTVpIIMkfIHaVHwUXv+frmbY6qNo3fm13Z7j6VXbHZcckCCwPAiw
MhekQfsKxf0sI7Md0dAJmSOBWVqXIkDKNEHq1dCxz7bGvYu1C5hkTlJfyRZJxpKyIvlY0nnyfKHHiPob
+yfbz/W46z6TfvXvJ+/xsbX/iDXDFfnI5YZsJL6Dl74V/f7Ox7vSlg2Blb24l+2wZUeCQAoESOZDxlS2
4B7gh+oe1NbeE6lNXNcTMk8BX4d3IVlZJHWVz50F0aBL9PmQ1MMVJvUOB7IFhw9BID2ZaMGue3uXQui9
Pf7de/Z0s2syL61F2M5dEB/J6zKcQubdO+Yzz4zabZZW/nNyb7HG3G/pLoy2poSrtBVGIBGGwfKHtJYg
IITeElhlp6uKQOxmh9b2UUEYbEXZzUFdflNXTVvVI5MvX2kE6GrmJK6IQjtr7NOsseKYPgRW1RNSX+HR
IJFHC+q1L968Wci9BsbSnwihLx1D2UM7IRBb5pmCe2xoGFug9c36ydB/ZglUaT2MQEzqzrA1Xrxe4yCk
vkqXA4jdagiLX6Xj6L6vFULvvjHt3TOKotkr1mbvFcgAvkWZGUNVKyzmINkcvXtV1J85SX1K5Z1Xo6re
TfoDkjpV5aStJAIQpGHSOtr69dHjSn57F3+XEHoXD25PnRpFYxDNbo2XXgMi/64O3vWrSBUSMu+p62Dh
k+3TpXEd+2VWwb1VjY4yla2q9d8X3lZ6LAkBrqHTw45JlMWC9tKWGwEh9OVGVPa38giw0ApKWcLqOkX1
9V2jfKb88k/bKXOtPDbyjbMggOwHVtWz7RdZzz7ndl2hjWU5eR1JayECyfp5EGjZ2BZ+U6/uWgi9V0e+
K84ba3Fx1TSkJb1J9eeuQG1sLJcHQuZdMb4tPYmY1HNHWHuU7lSXhQO61raQektBj5LVYKFnYgt9Y2u/
rtf2LoTeayPeLedLycjRLRZvwuZ48R0QjPkacswpLU1XnqQkdcs4t/Y8+pRXmlK53MGm7d2FqHdHk/ol
P5EAypbhTpc7fqMJobfse3pzx0LovTnunX3WJPPNUJ8aPQZk7r7XyDlfgC47/XmorKVVqTr7/OToVxAB
uN89b8oYtA80A+8eddXDe6gzDqpoN/wKHkVvfRUs9D5WZpO23AgIoS83orK/1iKgyXyzCdEY3yx456Fc
5qdUyePNgYQu13Nr0e/WvfepUmkK19L+Gcu6VxWKezEmQ0i9BcMdZav56oGH+XuVtswIyA1wmQGV3bUQ
gUSHe2jIh2jMBUYudyEra8XfKNdyC6Hv/l3DUi95U2HOeboVmtvVJu/xmtSZCilteRFg7fosAuOkLTsC
chNcdkhlhy1BgGQe17VGBa2LQsf5QEzmvIblOm4J6D230z5Vxpr6QO4plhluV9eW92EqpBJSX54LQQe5
Yw2dlef69hRCXx5UG/YiN8IGOORFWyKQlL00jBDSnZ8P8/bZIHMKxvD6ZZSNNEFgmRCApT4BmdgB+wmW
729XhYl9hdSXCdpkN7TQB/FP2rIjIIS+7JDKDpcVAeptxzWsUQbzq2qNcyaEQSpYMWcku5D5soItO4sR
yKoJWOp9ub2tsMo19f00qbNGgLRlQABBceU/xGvoG5dhf7KLBAEh9AQJeWw/BEjmlOZEg2jMFSiD+WZN
5oYWABEyTz9isIbgOtZxg+k36u2eIG+W2kXJXSs07slu8g5k9T5VuE9IfbEXBjxsikFxBtbPnSdGFvr5
50tw3GLxnGU7IfRZQJG32gCBejIveAWVt09RO+EKZZGVqIJWGxxkRxxCFQVqTOXkENyly1eKqzP9sGXV
VLnC0ruBqbZlC6W1amh/kLpY6ukhrO8ZcTf+Bsq9X4i8Hpplei6EvkxAym6WEYHR2zJ1lvl3QEbrtf62
gTKY0ppBoKJydgYFav4bUqdXKgvFakyLv/kkM6CZffVq36yqTHBSNBgEwdZMoXyEWOpLuRToWIPXba/9
ZGK5FBjn2FYIfQ5g5O1VQoCVryAYo5BvDjf7LcqxX6nJXIlV1OSIVIBdVpXcrVC1f74/7Jyq/OobQOoI
JbQYfyCknh5QTIpQgjebzYahf3tmk/sibakvFP2uXcwS/DUDZgbFrRNcZuCyDG8IoS8DiLKLZUKAOtpx
5Stos28BIR2ri2gImacH2NAL5RGZu6Vr/OH8kepk50/qst8NgNS/BWI6AZMlBCVkSOrMFJCWDgF6OqrA
zQwt41aU6H1pFCg3z5o6sjPMEBrxurRAui/p+l5cQzcxmYyu064/3ZU+QSH0lUZcvm92BOIiKyySYf3J
24pKWEcpF5HGSkkQ0uyIzfZuCDr3EW/Aut9f94ft9boTlzDe+NQJBnT5Q/Z3jDA4FtY69LT7WF1MSH02
JGd/LwPcQEa4bRrW95B18WptqbN0b32jV1nXGjAChHv8Wg3qIm6Cc4IRLfQoniN5Rx6XCQEh9GUCUnaz
BAR4Q2T5yhvCvJnz7oZlfjD1tXFXFDJPDyuDjHxgl8ESxRf9EefNelOd9oclDDYd0HVfX3XYuRWL6UfB
Wp9U2X4hdQ1O6j+WLs3LGkDZvuuhizAyUyYWwYcbN5LWlZ/DpKpYugsT1H6QGCeoPd40LLJ+3qKrQAi9
RcDKblMiQDKnbvaN4R7mhHePkbMPiMhcLPOUCLIbyRypQHbGcL1PwzI/M7IQoa4Xp/3V9hVHaVeHc9vM
0DhMVSeLSM0iqSODQFpKBEDq8KNXwc/9uU2I9Xh9ROqs0obCQWyjowGi4S31SqPk75U7GrKydyK4kxPU
3iZ1oIP/eb1KawECQugtAFV2mRKBhMyvC/c2vdJ2kPl+LJKBrcUyTwkhuiVkbhlF9yOwvs/WZL4R981Y
kGfGruJ86sqI/U++Cg9BataDICa6jYXUZ4A15xsgdZjpU2UFVblvwv1+uq7SdhsFj2JS52QqXkry19vr
lOvegUkXru1et9QNsdDnvKyW9oEQ+tLwk60XiwAFOmiZX/mXJ1pVkPlgbl8Wx8DNUMg8Paa8MYZw51qh
W/pgdST/AZC5qd299WSugw1HG3/rsftdDeXv98PqWoio/BHEBFLvdbJJDz6mTMTUh1SsUoO5S81C8Uy9
dERS5xo6G5eSmLlhGIE/5IDUvR+Lpc6oTN0MmuvSlg8BgXP5sJQ9pUWA6T4senHtxNMsv7pV9duPQz3z
Cn7cjcFFaffXm/1I5gbyzI2w5J0TDDuf0i7e9XC9M11KN5AKRXhAJvplnVhP9Dn+1saihIlVsE0N2k/W
BUpkYlWDKMWTurEoYizWzBwLBiYyHRMtTseMMzh6yhvlY9JoQVb3HiwLHaonPZqBkus1BdLSZV4EGmft
83aVDwWBZUCAljnJ/Oqdz7Kq1e3QyxYybxZWHSUM63CQZF46c1YyTyxEkLk15p6mrnYfo9fTaa3XN44F
lz5ek/uDnw1fEJZLiMrmWq9Y6vUwLfCc99EQHqbAsPMXmWPeeRrrzZvNmqVOMueECg3pg8fBUv9B77rf
EfwvrSUICKG3BFbZ6awIUDKTrt6r3edalnkPgrEepfWyxTKfFa453vSVibyp/pxSpeLpwbD9Rb1OO1Rn
mbM6nY6yhuj9ePF8taf9LejJ3KguD23tAiaB1zcuffC9k/J/DozqweGEd5/KSQBXPUQpnkf3Uq/kG07u
wsy492E1NOQrHcuA8WDjmvo0qb9UeaUbe879ToucyZXSWoKAuNxbAqvsdAYCtMxB5tkx7wWBEW6BPnZO
VSYjbfYZneWNORBgDrSFdClkj1dO8dcPXpUEXdX6J6Vm8Uam4H46tO33aHGenN0H1/zPYUJSuvQRTeAk
8vp2CaK0zzioogp/dswgd4fh2AeCdCSuoR6jhZ+TrJhxYBlu+ZPIJnifttLrgxTrlj4goPRtkPoJuk5B
909sfXiVLCzpbIXL/cjI5a4pSAh+4esqVQ+x0FPBJJ2WhEBsmWcKO48AmW9F7jPIfELIvDlQYZlDspWq
rRPl9ZrMaVUz6CppJIpaqdnipaGjybyqYxOQPYAsgudkAhc1vot76YDEXaVLSeZ0yQ/t7QblBw5Tnnu3
ssVST+BN+UiGMpF6WQ2dwXPhIfmcjmkYhVXKyRZbvaU+ZL8a0e/XqTU9FJAYxi53TnJor0tbNgSE0JcN
StnRrAiQNJAmRf1rBGDfjiIXfbDMSUKNbt9ZN5Y3YwQoOarXX1VQfaW/IX+NDmart7AbrD73KpV3Toda
HMkcEde8cWK5A6Qe5pxnWMrYoa4tPXFW6VJOEEjqUJaD7/hIkA0leJl50Nv5081diiQqC56Raph33mmN
F7+CmAQQOoITmYXA1kDq+ddgrFBREJOnsAdSB01JW9PXQAv+CKG3AFTZZYxAHEGNHN2XhZZ5K3WwtR42
vMGCUWoEQOZZSo6CEvzjkM98Yy0yPdkF06JIEGiRC9c+OSo1C5wbSs2S1JFN0G/vg4j2HarwyL46pmFX
Sz1JtcI+/ZH8MbA2owCuXiCbBNOlPka4W1CJq2BydYZVcC/Tu2TGwWykPuwMg9Q3RZZ615O6WOVLvb7m
2F4IfQ5g5O0lIkB3MCKoIY15EtzEN8HtiJVFsJKQeRPAYo2beut+pYL8s6OrQ84PEVQVZQkke9E55rCq
4c5FOtQP4SI/AcQwpd3sSZ/6R67TMkWwP/dYK7S29xXcv44sdey3vrFIDlOt0JA//VJY6t/uKbdwPRaL
f46UQUy2isDbsd+A8bla74qkTo8KW72lPuxwInaF1uLvRpGfJJ0yjPPQz9cIyJ9lREAIfRnBlF3FCOjg
KpD5eGkDItmvhUwmyRyiZLi5SUuLAMp19mchLzphBv6R1eH8HSyuwuWL2g5I5rSmC78ftJ5d2grSeHGq
gjaGkdXZBX2De/ihcXe28Mhavd9dLfWGVKv8iWqnO67dwt1INjVQl/lJZKlntcckb2+AB+Va/Q11RK5J
PbbaocF/GiYAl0Wkjgldt1Ul42KEFGZZ5otsendC6NNYyLMlIwAhkzhSGrnPb1T9A1dDKxzLt7p+ZGSR
LPk7emIHFUyEMqpSLvqGOrSyYbd7tWXOlL+kJQFxlz20uxnuweC1Q3U0eypBGO3xzEK2tIqYBjsIrW2Z
QvHoWS31OuKB+30ExPTNmgXZbWSTYNuKR3pGisgYsHMngdRv1F9BbGMviBb/iYPmkKf+t+j7VUyeslgy
YRxE97ioeSbddD6tuFaWsE8h9CWAJ5vWIaDLRW6xmPZkjntvRXrKN2AFwjJnWSoECElLiwDd4SDb0oMg
80PUkPPPMyxzkjkD4iAWkxnMUgP/b6L0sqZVx1Dje4qknsHwbbHGUOObHoBdLXUSz7QF+UZVdL+iSZ2l
WiVKOe24Eqo+Pemycy/XyyP6N3NMFITIvTBorkbq9lvgbfly1+FMC13y0DnaLWlC6C2Btcd2yhvTZqTq
wEVrjrvvhi77l9Wkx58tZEi13nWPAbLo061oPfXJ8h/90IcbPH+/Jtd6yzzRwL+2vI9lGTvCnP30JWrg
M+CuipQ4RDewxnfxNdpS56ShvnHdV5NNaPjD+bcZRe+zcPFzCYUTtu6xIOvPuTXPI1LH8ggs9S01HQEu
n7DVSB04D9lvh6X++Rjn7ps8bd6sHfCtgbk39yqE3pvjvnxnnZA5rDhY5u+HtfgZBF0hkhf/CZk3g/MU
vBpZFPr4vR8Ya9XI7r/RljmlWZMWi/Ooayib6+9QA7kn6aj1pVanY2wDYxwY65AdvMba5J46oxwoj0GT
DR2moYGqbu9BqdaPgWzofSGp85+0dAjElrp9lPVn90512e8GdCxEA6lHOEOA5Z3AOZk8dQupywQw3XXS
dC8h9KYhkw1qCJDMKQ5BMi8UNxp27iNIcUpu7HJt1YBa4AnTwQaR611yfws3+1q1Ifd7reS2q2WulfYe
fp7lG9DAH9wL5L+cBW2Qr84a34h5yNmXQ4/8jEg1Dh4WjnPSSOpssNZB6u8PXfdDrPYWf5yMffxSHuZB
oA+/FaypO4eYub22TcvysqY6GnHmb2t68vSpzveIxDwua+jzXBZL+0iijpeGX+9uHa31hbzxZMbdT0Bi
9FysD0KaFP9RKUtaWgRwU9eyrL8ITIeyrA/OkGXVSnsQ56HSnrJuRSpbPwLaaLk3usXTfuPc/aIa3xOe
AU/LV8wx1w6GjM/oFKsQsRBJ2hEfmXm0X2jh8wvQb8Kw7U/CW8A7Nkldxn9ujOs/0aQOrJ8Habm7g0J4
JMZ/WpZXT55GsZRFj4hxDn5nFaj//YP+nUUYT0+06vfa7s9lDb1lIyQ/vJZB28U7JpnzZoMbO24yn8NN
5lxKXeKMeT3JNZV+6BMy/5egMokAuFnInGvZVNobd49HXNodEOfpb6nSXrRMEkJvO4CW+6exjPJBfH9c
ZATkkjSSOku1Ip86GHEuCj33LHgZoslcVA0u6SmP8yNAsR/K8v51JvTuRRXCR0fLHXEMw+hooM7H8tW0
R+SCumWODnddr58fGfm0aQTEQm8ash7fgNHODJBCg2jMJWEe0biUGI0i2TvTYliVIUU0OXXSS6XtKJiy
Tp3ilOMAqek18zia3SqUTgxN8zp9mNXKSojzgLhhkXse1F/tD2cKpVx1yPgHvGeo0fOjyRwPRlvs6Ie1
3+AY4wuIkp/Auv5X4T2gm57rvYkrXh+6/JkTAU3q4aD9TKvk3usX3MMxifpjzVPT6BH5kDmObEbbGYWl
zqBTkvr0RGvOr2iDD6anH9PP2uCwuukQOuNC6CbEO/lcqG6VkPk48pHXOCRzEhBv3ELm6cd2SpfNdN07
/afl6GZPyJxkjQbiZIAUUtMgGXoqqqtdpwPW/CpJcqUm4bw3REVG7MG/h3zvxVoQhJ6ZOIWNR6rfo7gN
Jh/+iP01WPanQRCHZM9rgscrLR0CfcAOgZHO06xQbVeb/vIkbaknKYT1HpHh/MbQK50HSx0TJ73zzohd
SO4Qsoae7opYRC8h9EWA1pObkMzpekWDaMwYRC9eH5M513GTn2pPQtPcScMyZ7ET17sVAiKRmAvJm6TI
xgC0AogUr82x4tugu345XOw0mFfD4uWtVxcZwXifBVL/uj7GeulS/Qb+MC+epL7BuQK57UPQn8d0gKXh
hNQTiBZ+RJ76BEh9wH6SZfXfq656+GmR2A8UAtkaSN3+aOgV/x7xF8k9vDNInecha+hEoSUtuRhasnPZ
aZcgUE/mhSI1vYe1lKVhrJS12CVAgsxZUcv1bgKZH6tv0FQKqydz5vMza2DMPcfIOV9SEy7CzFZVnIdh
jigyAk9MPve3EETZpAeDkzteF/WNpI7UOn99bjP050/QH0VV4mLPQ31neT47AiR1YN2Xe5yVyUAhcOcz
dQEdpiyyJaTOZY7hNZ9AjfuzkZWQ3Mc7h9RnP3l5d4kIJBfCEncjm3ctArQeE8t83P0B0mxQ/ANWBKUs
69OZuhaAZToxpqaRzIula0Hmr9B7JSFSL50tyhrQxTp0CqCDqHHm8ysGH67yGmmiR65J3R4BqX9HHzOv
i0S6VL+BP0y1o6U+ZH/HCPyXsEqcrhanIGEqLS0CkdZ+/+CjrdC8p2+s+JyI1OMCOiT1Y+D5APbBsPPp
sFR+FwISeS+np6wTSF3W0NNeCU32E0JvErCe6p64gkE8CIC7Da7i42FdQk88vrH0FBiLPNlovbCiK5UV
vasgFPJavac6r4cm8yRroOB+GgFPH2JAGvrxBt1Ov1HokWP8HfuVWHa5Va+lc0LC66S+xZY68tRvBves
g7UOeVlUjRNSr0dpoecgdaQm9g3sDm2Cu7PXeAdiYj2lxYb0lqyvvs7XAYnDuYvDUukdbZ9lkNC4uNwX
GvtFf95ON4tFn4Rs2AIEEjKHipUVQs3KcdZFZN60XngLDq5jdslbV1XrcRe9b8AyP0UfeT2Zayu9LmvA
tt8DnGnNJhZXu51spHKWt19kbS5Nq5yxKE99o6WO/PnqUP52LLkfhXX1SQTLgdTrlO/q+8vz2RCApv9k
RWUHnMAP78peUzq4wVJn1TJa6vitBiP2l0Dqb8X6O6eBDJZrX0udHgZpLUFACL0lsHb4Tnlz5rruzaGt
Vaxs51CtarVUidEOh6XJw6ej2o/IvPQlkPmb9PZ0rcdLGHoNOlnOGCtepbMGXK3+xrXpdg40BKlj2SWX
O8y097pL3RDmtarcDFKHRYko7erQmrvN0DhMVaZc1YeSsJrU2/n0mhzplnZHPnplkh6OAZD6nZlNOyk+
02ip87cakfolCKp7EwIpMR00cG+PglhbeniL27kQ+uJwW3ArIfQFIeqxDjr3+aCKuh5lOR/27qGKlZB5
09cAb1gBIpAzxs7iZ+Bmf4eON0gEebi70brYBAYa5p2TdeCZgbS0aM266S9d2Q2w7ALpUmPQPjBTdrdH
gii4bpI0q+RgqEUPS70yYv+TFQaHqqmJh+FGBqmH0/n2SV95nAuBqCqelclCj2BLZpP7ooZAOW5FUmfs
wjCqHE54r4dVzylhm2YZtK/zYK4B6JT3hdA7ZaRW4jg1mfMGXNwrM5W9F2T+nKiSl7jZm4Cfd6sA68yW
4bofrY6sea8mc+pyc52cjcsZo7gBI59bl9FkoCEtXkq5dgSZ67PgH5J6Jcw5z7Isc4cqlJ6g06x2JfW4
JOvUSP7nfhgcDOGZB3SJWIVAQWlpEUBVPMQiWBkztMxbo1K3WNaox1qnDv4EegDO5cD4ZAVRQWWwjB48
Re3UJA+9ZaMhhN4yaDtsxzUyLz3BCo3tUK16hpB502MYETaKlYRu6YPV4fx5OnCMu6knc1pTjE0ouFtB
/C/u6EBDZjtQEGXAfgqE4HeosYm/asidTiDUljpSr0bW/NI3qgerydL/6FKxCu5jaWkRQFU8lLo1sFzB
UrebvRNmlLo9A14Sbak7m1S1vB4TgPbTAwhNcbmnHfEm+wmhNwlYV3ZPamxvKj8FbtHtvDnrm7SsmTcz
3CRzgznBoeedEwzbF8Z52rC54yAgTppI5oVwN8Qm3IMUwEO7I9AQ7vdynDttVLfPSLNKUGSgHC3Kod1/
5xvmWpD6f6pBpPIpJaSeYLTQY4glmaTUrdX3bdSvH0pEfWqb0lIHzv5Q/hoVVF6tJwDtJPIjFnptqJb7
iRD6ciPaaftLamyPTTzDMv3tCKh5vL45S2pa+pGMIopNpg2xSAlygz+lyZzFS+rJnDfaq93HoAjHdixn
/E1XxSbQUp8sMc1qT5D1PdlN3kGNwVsxnLTUObEZyv23nwnWqrL7a0yCQOpiqae/4LA2rkvdYsWiLzeO
ZZtTIlKvyzSIcfbX2zcgqC7SPaDIj4EJ5Wo3rZO02gfRnd8vhN6d45rurGIy7yu4f20Z1Xt1je1JHWXd
mIKUbm+92gslYxFRzMjiUun0YCT/Bb1GPlRH5okH5KqH9oEY6o4uXs5AmtUE0qz67MAMt2XGi0c1plnF
l4he6wWpn5T/s1911hol7+eImBdLvblfUETqU2WFa+8Kq+C9SWcaMD6DtQDYiDMCEv0Nu92EhIvjtciP
SR/8Kov8iIWuh6cVf4TQW4FqJ+xT19jefyq76eGD/NC4mwIWLaqx3QloLPYYQeYIOkJ5cjXpnaqLk/CG
Src6c4TZYpwRBf4sBCnvwHLGkxCbwGCwSMpTd+qqP3GaVbYPaw23s+yrttRpldc3kg2xep3xUNUoHYpl
ip+xLjy6iPu9Hqf5n4PUMXGc9BSq3H3NHPPerq+92xjdHpN6HJBYXe/cAh59IUg9UJns6pK6CMvMP6pL
+FQIfQngdeym2jJHje1NOw8LrOxWWlRawIJR1tLSIuDr4iOsP1KZWo888yu1K1mTebyLGOfsmPc8RIFH
HhDqdNM93d0tichWoZX5gbVp54kz1nl5/sSKuetDe7tB2T5MeaV7ECQopN7MtRHJAgdYJguNXO6LqAHw
d1GcBsVlYlKPUwcRpHkb5p/rFEvwrqZynyFBcc0McTN9hdCbQasb+sZudrhDj0FO6x2Igu3XwhVqFwuq
G861VedgwGUZFR2B87L6Kn8od40O9qLVmbQazqXDA1PdBZW0Ndod3SuTJgZvsdwr10v7c9dBKvZ1mtTr
XcLEilHZfO+NxoS/d+5IBAneIaSeXESpH3kfD6n9b9j2Z81x931avIiFfhJSj8VoqusH78QKEZX7piLl
vlVxv0uUe+qhba6jEHpzeHV2bx1hvP9UpuC+JFTmj1E0w9Kz9ZWrsd3Z+EVHDzKHyxJFRwzfPx5CHt/V
ZE4rKGkJzpvd4+ARvRP9e3XShEw2lH2tovzroH0l6gG8RVuPo1vgKo6tR2JGSz2uOgdPx9Eg9R9GpC6B
csklleIxupeXNKl/3Cx4H9KkzsyLBOs4y6A6lINyn38EJvJlCNDE7vcVVO4LouzOFOckXZpEQAi9ScA6
tjvXMEE6qGn96tDMfF+ZGHrmtAqZNzGkIG26KuGyZNGR6ohzi14jryfzBOdC6UQYqTfDkoc9P9XLOJO8
faiXKZVzLoH1+G5dYa7eeuQIsMgL1fPQQOrHwf1+o3IkUI54NNF4PzeQPeEbdm4jvHAfQcBmoLSoESSH
2WL3e2Vktx2moSDHW4YcL0l9BZX7kswPfUDyZzkREEJfTjTbdV8kGbiDrUJpGOvl12s3KHNZw+gG2q6H
3WbHVQV2WZB52QzMI1h0JMqpTqxIWJx0HRNnphFl+q6jYJx2O8ukiWplXOelS/gzsB7P09ZjPdFwsKme
x2I1aCi/+kqo510LLXyuqU97P/ihtPkQoKltwsvhh47zfgQlXqRFjc6HS366RK/WA6gMOf9shYpyvI8g
w4VxHSuEs3jc5xvApXwmhL4U9Dph24RkNrunYc1sDISEWyvcoKhS3QmH3ybHiPzqwQxclEXTCA+rbMjd
22CZ06VJNzJcx+a4x4pXV2g3s+BcP3zRvcYr0Xq8EETz0RlEw94sVpOQOkvNut7VusANyUYsu3o853ue
kHo1dOyz4ZW7WGNHtcKE1GNLXcvxWsEhyHB5cFqOt8Xu91Cqrc03eEv5TAh9Kei187YkGZI5SWbMO0P1
2d/CjxaeNbg/hcybGbmKvtFNlh6yjPAQWjW6JjWDjNiIM93HcBkjwvgcRBp/Ge5lLJ1r9QyZNDUijfsN
XL9eiUTzDyD1z9WIBrr2ta71pD7kvA5Fa76hST26dsW8qwE17xOysgUvR0Xlc2chfuES3ZukXihE12Uc
KKdeu+bfEL94CISBYo39FrrfeVSShz7vwC3lw+kf0VL2Itu2FwIJyZDMC+67QDJf0WuYWtEscmm21wG3
7dFUtN74ZOlPvhmsnRrK3x+52SFhykZrZ+NGg1YlLPNRw7E/iRxzRvywxIr8tjRIM/4wSAtE41XDvP1O
WI9f1T241htb5vo1ST22JnXp2WLpiyB1rrFzQiqkrkFa8I8BOYQMJkRVlubFUtA39RZDQ1xui67PRI73
dbv9KtbY/6O+5rX7vQWWuozcgoO2lA5y01kKeu24bULmmmTc96G85T9y7RKHChlSIZkmhowFR7KYCP3B
N6y1ami3X2vLPAmA4w1RuzBHA1ianzKc3PkMRsL+eReU39X8QINoYD0WkZOfz70ZRHO17l5nmevXNRdx
aCCb4EzD9T6D6Hch9fmxbfyUU0tivZNY26+vYV0/gdLudxTO0Rr7Uyic4/0hIvVw+UV+ojmC0HrjKC3b
K7nxLBuUbbAjkjkDjTSZF89HANLHY4uRBydjnXqI4E4fRDDWZOm3vqFeoIYG/yvSH48tc7oseUNEoysT
luZ7aXHGGLfArEl94J3TkUTDnPyIaDagyMgN+uAjy1xHu+vXmtThBcG1XR1y3gtS/1hM6sA/GoPOOelV
OtKI1LPRBMreYBWK19awTrwitNQZPDu053/5vnEwjAAUzsFvIGxFoJzweauuBLnJtwrZld5vEuyCGyDy
zD9mOM6oWIyLGoQp6oobZe8XfsaHZe78Ud/oEtEY3gDpskSDtXMlXZnapRnFJQiZNws5VfOKKL/qOK8C
qf9QxyQw2p3xH0kbHUXqFUgd13h12Hm/4ZZGIRPLdDj0EFJPYErxGE2gHOcklO79ru5f7xXhNU4NhQ32
//iBAqmXfoPCOYx+X15LXYIbUwzV4roIoS8Ot/baimROSwY/FLh/Pxva9t+DzMVibH6UpqgnHpa8f6lW
7EPUSWv+0kDmJBneANFgmX8bLszXaQszSksTMm8e73gLlF91PZL6i0E0d6qLf9WvxWYoC5s0kjpTrzCh
qg7bG6H9/vcYK9y/4JXS+YFJR3mcFwE9gQLWtv0KYH2z7strOplA0f1OS/1k50++7x9ilN1/j6rhLSOp
i5b7vEO0lA+F0JeCXjtsm5A5jgUVl74E9+/fafdviHWzaD23HY6yE45BkzkmQjuQLH2oOsXYmeSV64OP
MwZoJcIy/6HKOydoMu9+XfaVGruI1G3ncPMxj7sLxO1oWViSS9Jo2bEkLUgdJWo/AVJ/N0vW6lViIfUE
pTSPfdr9btvHgdRv08GIWq0v9orQUudk6uQ1/1fNO2sxwf1/nOhix8trqac5UunTFAJC6E3B1Wad6f6l
ZY4GkvkGlLXepn+oDIIRMm9msGAd4obllbb6xn8eASu8nKT86Z2QVHjDuy0csJ4FC9KxX6wtSiHzZjBO
0xdj4E2hVvzzUDP+XvWtnY+aUdQlIXVMsIIR5x/Dkvt2lA+llY57WeQ9SfNFPd+H1y69Ijl7naVKd2iv
SP1SBzX2ed2/zNiJCe5hoVf6p2UkdVlEb9EFKITeImBbvlu9lhu7f8eLFN94oyZzBhpFAUctP4Su+AIG
/ZDMXe9WFFmJ6ndTgpQEzsabGi2WK8M15p9Ld8MtfJi+EXZv+dPVHtY+BHJOoWb8ftaAuUNt8h6v8efa
btJI6tEEC6Se/7Ka8v4WWgGcwnIiq5dEkq7yOC8CegKFmJHDrMc+fqv6bphLcNVb8bqPlpncoJQ7HJOt
7RGpJ+qI8+5bPlwFBITQVwH0JX9lPZkzYjXvbIgt8+lAoiV/SS/sADemNQj6cb2bkOt8bCRyAjKnpcKW
kPl1xb3NrLsD+fwH0ILEJ3Q/SmsdAn0IyGLa4FMtM9yhrp14WqRBjtSq+kZSxxj5653L1ETpFCghgtRR
n15IvR6lhZ4npH6Q6Xl3qyv/skaTOq99tnjipKvhPWwfQS/WMmjsa6/iQgcmnzePgBB685it7ha0HpPA
rHH3RmU7J+koYbHM049LpFTFHGhY5u51IPNX6I2jJYyIzFn+lBbKVeV9rIq5wxh0nkHLEf0aSSX9t0rP
phBAoFwZudP9ucdb1coOVSjup5haVcD79U2v94LUR5yrWJdesT69iT9GPCmr7yvP50IgWuqw7edmMn33
qMIjezYsdSSkDqx9I7cOE+DbtFdrsWvqWuAKh3L/FgkknWtEFvm+EPoigVuVzVhiktYjcnJRX/pW/Khe
HrnZd7nJrcrBdcqXYvkuRA3oPCzzorvJH8q/Rh95ndejpgZX2PlMK+PvUAO5J2tyETJf2UHmOu8kpEv7
cnuiiMi92YL3fExmQeq7WOoJqbMuPerT64M0rYyQelPDhaWO0lSYc55thZl71dXuY2aQevwbwQT4hZCU
vVmT+mLy1A0ENkprCQJC6C2BtQU75VoWS0zCFWZt9m4HIb1Ir+VKYFYzYIPNYXVrMve+4Q/nT9Yb15M5
LUCk7mSv8Q60QnM7irLsFZP59BpuM98ofZeKQBbVwCqo2+0EYXhXprATQYu01Gchdayzsz69EfgvYb16
WOpcgoo8Lks9ip7YXntFIKqU2xdVf1GAqPQETeoJ1vQM1krc2i/RJW75W2raUtd1DrDZup5AdSVPUgh9
JdFe7HclKVOF3w9au3tbEZl6pARmNQ0mI2t9TeY73S9rfXDugml/8RJGUg41M146PPDDu0EiazSZGIaQ
edNwL+cGWM+tTFZRkrYPirt3ZMbc4zSp1wfK8etiCVOIz9xsBOExunQt69cLqTczGAxK5FLHPlYY3quu
Le/TgDU9hJwAo0Ulbt3r8ZviMkj60quJy/3oZg5L+qZBQAg9DUqr2YfBKVzDuiHMm+EedyHKdK0EZjU9
IIj7h3UBHXDqgfsj+bdrQZK6HH5N5iAEqOwdi/vNnSCPflWZgHXH4CDOBaStMgIZVZ2qKpiOoWXdDC/V
CZrAk+Ct5OBi6726Ib/FCIKjsM0UguWE1BN80jzS6zdBUh98glWt7lBXPfL0ZLKkN+cEOCH14fxJaqc7
rifKaUldXO5pRmFRfYTQFwXbCm3EmxXXBxGkYk549yA/V6Ksm4ee63WBsnMgc/ej1AOP5EWR5BTn8Oto
dpC5VSidiOiEW0gamjwiBbjmv1G2aBUCGW11c4Jl9X0boignR+u8VJTTinHR99ZIfc1dZlA9HMFyHrwt
JPX0VmSrzqBj9guv1ATiF/rtvayMCff7LkGJ9aQ+kh+Bx/CKGqkvWB7VlDX0Fl0HQugtAnbJu03IHClT
3yebOgAAQABJREFUWMu9F2S+H4NWsN/GKN8lf1FX7yC6cUD3G2T+oepw/jztYucpazIHCXA5A5MmkMOp
sMqv09Y4ikOjBwlAWvshYKkg8DHhwi8hd5U15r1ZK8rdxhz0maRe2bD7T3w/PExVyjsRD8GlEyH1VGOK
SZMOSiwzKHEPKzTuUWPu3+igxGSpg6Qel2H1h5zToJz4dU3qIZa25iN1sdBTjcBiOgmhLwa1Vm+TpExt
+suTrIqxQw06+0YpUxLN3gT0JHMD8QYmpCvPBZlfoN2E1AOnMAkr05EEsJyBWuZvhSVyOdZpYcuDLGD/
NfE90nXlEUBhFpDGpKcgivJVs+C+Sy9LFaAWx3FNWhI8d7Lzr77Vd7CaKj2ItWEh9QSfVI/wEk6B1LP9
ecs07sqOeS+I3O/xvYhVBxNSH3HeDPf7l0HqGcytGIy4y1oVfncYHSNMguJSHYB0agIBIfQmwFqRrpz9
8kYEMQ3L7N8OcY0n6yAVscybgB+WA6VAofMdeu47gyHnIsWUP+qAJ2S+ebMZkbl7NgRjvgxywM1H32iE
zJtAevW6MjALZFL2Qniv/tEc3/n+OLhRl1qtHVdC6q/t/zc/zK5FGtyfdK3vxaRb1Xbaa0/gfo+CEnOB
EW7NjO88vMFSJ6kzHgUszvgUY6f3OYjPZEHe/B3WkXrtKd+X1gIEhNBbAOqid0nLnJG6V+98FoJRtsOa
eKwOTpHUtCYgJZnjZj9gK1UuvgXSoJ/XbvXz18ENCAuBNx6W4kQJ1Mx4cRQ14y/ChAlWhr7xyO+hCaTb
oCvHK8T6LeTG8x/BeH4EYxwts2iCiY+QpM6J8sjAb3zDAql7f8BkjxLJ4n5PNYiaiDMRqWejTIPx4jEN
gXJcwhqlox2m+Yjzd4bnXYQAXi5bcTxqTB5/neCeCvfmO8k6YfOYtWYL5j9TNONq97nQuboD6327aVEN
xZSpXX8PrTmELtgrSdvSEqCT3mn+8JordNUoZgkQxLqodpSZvSh07LNBBrQW4uIeXYBA752CSRpBfEk1
dJz3Y1xzVcN4tx5vuoITgudEmXEpQ8Z/+Vd4a63Q24blmKfCwpe4lPTXDDINKkgfzGZCv/pjYP0SBJne
rDUBOGmK4lJQyhmkPmSciwnWZGg7H0BWDn9jmHzFqyEGxoLtlz+dXh7Rb8ifpSIgFslSEVyO7bWb3ZjK
bnr4IJA585930/nPlHMVMk+LsK8lP6klMlUeRpAOyBw3cFaNIohMs9E3HFamK34FZWZJ5iR6/gbkd5AW
5fbsR8vQ4niyfLA17l2qD7NufVe/jhXl1Kn2//p+sBa1vn8JUmeQKUldWjoEkGlQ8Smxi0LCPwDWr9RL
hPytsfE3xjgVTKYQt/LB0HU/AEs9WsZiMBwpvOYZeb7eRP4sHwJyI1s+LBe3p1iZLLO5dFhgZrbBuszB
tQUSin8gi9trb22FJDNlZqKbRrXyKijAFSIyjy2BOiU4lJm9EsVszogr03EbsRK642phXXRLj2s+dzqk
ka/Sp0VSj3Om9euE1Fnru1Q9GAGTPxdSb/oCQKYBpfjQMpnvWIXia3X6YBL9zqWteBKNJa+PhKXye4Fx
FNsAB3zA36u0liAghN4SWFPuNLbM4Zo6JgyCO6iEpdeptGWech/SDWIj2YwKqqiG7R9P6U+9XsobNxuD
4WIlOFjmVLV6XUzmtCiEzDVIXfInKhsMjX6IoqyxT4b1eL0+s7qcaf1akzpy19+4x8PBpH0ISH05a313
CZgLnEYY4jfn+wr/q+zgZqtQPlmvqV9CTQA0kvoQLHKkhQZDuc+EpdKZ8Dz2aV9YGCKdRForEBBCbwWq
afZJMo+UyV4SKvPHEDOxpsVMZM08DYToQzlQio1g2TRch2CcW/R6HtdL2ZhjTv17FrMZd2+BZf5q3Ozp
Xo1uOrqT/OlCBEDq0Gxwcq+GpX4zjEUEQSJYktdD0rgUw9enGV5QegC1vt17olrf4n5PIErxCL870jyZ
7tnXfxW0HN4QaQIkOIPUIcCrSX3Y/qKqTpzWoKIhHvcUEDfXRQi9ObyWp3dM5tb4zleDar6vSz4GVbqh
pm84y/NN3bwX5sZSDnTCDIwjq0P522vBOTxrWgoMhrvsdwPWZtZwto+NyVyEebr5qqidG4JMXUze8vZx
VgHFjLi0xeshsSDZj69J6m986oS/t3MkSP0OXUFM1tRrKKZ4AlIPoQlQUtByuMwc886o4cqJFLLOI9xR
OIdxLQ+WzsA7f9b7LUqAUAp8m+oiLsem4FqGzryhwDrAutOwygyMIcBExEyahxXqVVD9miq5ZmAeVdlg
/6yRzBkMByu98OBupuq7DXnKB4r+ffMgd8cWyByxUffe837q724frY43PE3qUbBkdIok9SgTAgGT7g9B
6i9GeVB4cmLxlO4AotVnwYA3A+miRlh23xUM5y/WsQuJ9gO/vVCwmC6qPSYkemnLjoAQ+rJDOs8OYzlX
3DReD0L6Jop/4NrG7FaUyeYBbcZHMZmXH4Kk55Hq5Px9DWQeez8UJHMzFeOOMGc/M1LZa3D2zdipvNHV
CEwx8C30vPuCyeBo9fo1f0mK8dTOmrEWXJ5Bw+/zJpD6y4TUa+ikfZKoM4LUvXO1oBMDEhtIHa/jmJa0
O5V+6REQQk+P1RJ6TsuMwjJ/i+p3LkHhA+6Ps9UoOnsJe++ZTZnuQkGQCe/PvpGBWtXAr2cl80L5yVbo
b0XfJ2mVPRHm6ZlLZO4ThaWeo6Xu/tbPmkeo19j/25AJwQ0bsiGK1yHm4kTok1dgd0rMxdzA7vpJJOxj
26bhlj5QHbE/whQ2dIokl3ftLa+XFQFZQ19WOGfZGbWlR7dEmuFjpbPUAMicMqNaz1jIfBbEZn8rIXOo
fPnVytoZZJ6o7BV2PhNkvgOuvyepMtymcjOeHc+eexfucxY3GnSeZlXVDlV4+KnRsgzUGZNWFw2P1MeT
EHOxCdHyJHOSuriIE5zmf4w4BWIyYT53ITJ4PqzFfTYCwdFR4Zv5sVvyp2KhLxnCeXZAMt+MRA3cKMwx
9xzIjH4SFmOUoyliJvMAN+Mj3IghAFKCdVWBdQVhkAbrimQOpapswT0gCNXtWM5YowtKSDT7DCB7+w3c
7sKworXcJ73/88PwKDWS/4UOmKNKY9IaLHX3mwise71OhYuCVuWemeA0/yPvcwGWLizD9T5ZHXbeB+wN
pYk9luedf3v5dBEIyMW5CNBSbVJ38WbGvQ+Gdu7DCMyJ3FFC5qkgjDvp9U+j7P1bNRMcoU7C+mcci6A/
j8mcBSOQ/vcjRL73R8I84iZtBuQe6xvFYVTKRdM0jq68FkGVSexFAkSdbKw1VrxErXHeAlKH2AHEa6J8
96SnPM6NAEndZ/U1FmyhxrvuWifBPPem8sliEBBCXwxqC22TFIaADGJmrHhhmHfOE83whUCb9fOIzEve
v1SNqaPV0J6PNJB5kss/5h6Huf/3kZNuTufyz7o/eVMQSBBg2iOriE1CkfRF1eE122ZY6pp46Go3QuiW
fw7a/++M5YJFYTBBceHHiNQdFGpx3a9gKeNtepO6CdPCu5AeaRGQNY20SKXtx5sAtYxJ5iwAMk3mxFrw
Tosjc4Ftutm9HdWHdx4WkTlT/mLRGFrpEJCBGtirw0zmZgjzmEgBlFz+9Pj2eM9aSdB+eHbuwG/1xVga
m9ITxgQZ6pKPcvUcxUaGnXcZRVQQIzHRlcwgL2lpEIgkeVk3Ie+8FRkE39AbaUlepLFJW1YExEJfTjjr
XEkgmouhVHWWzOgXBTBUvkDmXmmrr/7jRbr4Qy1XGLb4JT/N6Fz+cfcUWFlX6Fz+MKQinAjzLArunt4I
0sGZDK4dUHRwgj9kf6fBC0Ro6jxu5njxAqNWQczA/VNHcPc0gKlOnkGFIZQd8wgyLHpX+cPOKXq7uniF
VPuRTvMiIIQ+LzxNfFjnQoJm+KWYjZ6u19yiHHPBOTWUsJIcLQTyI/9++zhdvSkh8/ogw/HiW40B58tR
+p/k8qeGVzrOhkBUqc/EfDCobPDX58ZmkHrDted90JCYmNlwTPNeRZO6W9qMydOQ3kBIPQ1uqfoI0aSC
aYFOdRckXErfwgV7mo6KNSDlKgE0C4BX9zFT05gmVPS+hxn8y/Uno7C6RyHR2XBDdd8L9bdPwR1PxycV
qmQpow5GebooBHykV1nIkFBqsvwmFPn5hpaFpRZ5omrWeA2ei2vwE5K1sgisa79z9ztYUz9B76HuHrqI
PcomMQJyI1zqpVB3ISIadkyTeSRGIWSeFtvIHReRuVu6rkbmxJZkTpcn012Q/oe81lGk/5HMuY4pZJ4W
Y+m3EALTmuSDua+bm6EZQTlYakiQyNlYQYyqZ/AYBcPOJ8OS+y6kU/IzU08sdSf5syAC1IZgkSTHeRUM
oO/r/tQA4ORd2pIQEAt9KfDVk/m4B2Wp3InaMpf85/So1q+tud7VKODwOr1xgm1dXAIClz6FSOP3xhkD
nIzK9ZseaemZDgFOFA3W74ZU7D8EI87HQei81uqUzkDwtyF9DYTPYiTGYO4rUC8Ub1E6fOt6xctrrvdj
/xconsQgxGR5ra6XPE2PgFjo6bFq7NlQZ9u9MSJzFnSQ/OdGoOZ9hUAZWEFRoMw3ZpA5iznwR46GIMMv
azL3EC0bZQsImc8LrXy4SAQi8oZmhOHYH4NH6AKtdMadJcFxuoIYXPG01EdsyDh7b9CuetPgtqzNIC0V
AnFFPMd+ofXs0u06biGpgJdqe+m0KwJyU9wVkTSva7NI1tn2bkFEtlRnSoNbY58oPxWiE6hd/SWsWb5D
f5wEFyYWOt6EW+4KkP4pEpfQCKC8aiUCnEgi9D1SOvss0tbeo7+tzmOkXycFl8aKI6pvYJNUT1zUmEQp
qp633TfsdVhaK4ulvigcJZioadgSMscjyHxLROZYD5JSi81ASTKnLGQGub2frZE5b5Y6P3W6IhMyBq6v
kblC7rkEGTaDs/RdNALazW4y7TTM2+/WanHcFz1G9BwljboIIHV/JD+mqpWTFOLqlGnxc7HUE4wWfmR5
W5L6WjP07lI3PJCPaqhDd0JaUwiIhd4MXAmZXxYOWLnSbaizfIjU2W4GQN2XLvQQP17L8NyPVofz59Vc
mfVraCB3az/v++h3nJSxbBpj2WD5EODkM1kWuhIBm6fqXdd5kKLXUT0BTPJfhknpTcqE992vitBRc+Og
lSF1mdt++wh1ovHwjPTB5vbXc72F0NMO+SVUKTuoogp/dswwdzsirZ8H4ROxzNPiF/XT6+EgaUzE3Q8F
w/kLNJlTWY8RxAnG3wv7raL7I0TBHg4LiXEJ0xWxmvs+6S0ILBcCSf70dciffo3e6a6knkgRQ3UOs4Bb
VCZrwGoXUm9qBBAohzK3Rsn7ZdUIj1BD+QeE1NMDKISeBqukGMj14e6ZSXdraDv7I21KiCYNdtN9SOZR
9HDZOzcYci7S9aeZBqTJHO50ui9vCPPmpHc7cnwPFO/HNHjyrB0QqEVl/wCW+kv1ESVeu+TwkmJBm8tH
hoH/I9QXyEb1BQykZNHYl5YCgai6Yrn0Oz+jDte163ctnpNiJ73YRQh9oVFPyLxQ3CsTGlvDQfsZus62
rJkvhFzd58gxVVgXH7RVOFE+KxjKfUHnnJ6PdUaSefJjBcZmqO40cs4zZcJUB588bSMEElJ37/Afdl6s
J6EzSB3R29CFz24qHRyYwRbIEw9IBcAmh5DiM4MQmZrw/uAH5mFqQ+73tftEk7vqpe5C6PONdkI013qP
s6rhXbjAniJkPh9gs31GMkfO7kBOQab1LQiA+6qOYF0Xk3kyYdpUepJlBHci/3cfwXg2HOW9NkIgicre
4U/ax6jTDG+GWzi21LObvAMDK7xdZQfyamqygomtBHqlHchpUv+jb1go0DT4OyH1+cGTPPS58EnIvFB+
Msh8uxoQMp8Lqnnej+U0+yGn6Z2myZwETjlNWuYFWDJ0s4/tfIZlBj/BhEnIfB4w5aO2QSCJyn5Bpt+7
R1318B76Oua1nbSh/ad4fVc22D/D/eNQyMk+pPoHmaUBUpeWCgEqypW9iurPPdYK/Xv7cZ9ghUXFyZK0
WREQC302WBIyH5v4K8uobgOZPwauH/4Qp3+ws20n79UjEBe8QAaPX13vD+WuabBiSOZ0S465fxMYsGD6
7d3UZEkwrkdQnrc5AlEAlyqVfu0b4ZFqyPljwzXOo0/uJVc98nRU+N2m+p29MLmV67y5kQWpYzI0WX7Y
8sMjpk7O36dJnZMmaQ0IiIXeAAdekGgwC+wbKz7bMqv3Ynb4GD1LFDLfFam5XyO2FyUpo1zdauVVM8mc
KT7GVKZQOjQwjLtVdlDIfG405ZO2RQD3CgbHDub2xcW+Q11b3kdb6vUWJC1KkvrrdvuVn8m8AGT+3zAQ
xFJvbkxJ5hWo8e3uW+rubME9QJdU5r1aWgMCQuj1cOh1L2Oq7xr3ub6h7gHRPEpbjXT9SEuLQFWZ2Qys
cmX4/vFws39Xz6bpWmeL1xYzm90XhSHWzDPZQVWZYGqPYKwBkj8dhgBJHWRjP9Gq+jv6CxPPjMimzi2c
kPprBv/TD4y1iCX5D8SK8HoXCzP9YGfV1ESFsQhBqO7Kjj3yAhoF4n5vBFBc7gkeMdFkr/EOCny4gPsQ
xcULSIgmQSjNYxVpOhnk3lYMFbwYojF31FyO3DoOgLMK3quUYd6AdXQR30iDqvTpBAQSt/BO01BHV4ac
f04mr7WDTwJAmTETGNtC2346UjMrSOaUyWwNpAWfVJE1kEHWwBTuMS+sDq/ZNgPnBXfRvR3EQufY1qzG
0mEg8224YEDmjEiVH1oTlz5mz/ihVStl0zKO1GQeL18gsteIRGOMilVwTwbp36Bzcv0qI+ClZGITIEvX
tkUgcgtn+9cEoXEXl5NmWOqxTCzFUqp+9eCw7N0HkSWx1JsbUpI5DYe+UJm3Zwrlo8X9Pg2gWOhx0Aqq
Kh2DC+SHcAFbkRCEEM30ZbLgM65vwSVWKpqGcVSDdcJa0luiUpOQxTwdMQmXoh/4PIzS2RbctXQQBDoK
gchLVZkKDDM8tjqU/3GDl4qnkigiFkKoTnp3QnXyAFGdbHKMGaejl/bg4DDUcdUh54czcG5yl93Qvbct
dFrmWN/Ceu5x0B79sQ7kqk6JVGPqKxvzQabh9OdA5uUHrbDv4BlkvhkFgFg3etx9N4KHLlWTLsqyhFSN
i4LmUn+XdBQEOgIBeKlwD8lkoJFk/cga816hU61oOCSNEtIUoxky3MB46DCswd+LuhAM8JI19QSjhR5D
GFw+ZHWtDG5B5i3WpkdeLiltlOLs1Zas527GD06Z39UwhEEVlqO4gFNfEwhKGcCNaML7kx9mDlcjA7/R
WQIMVklqR6PgijnufdCwcx/GemGk5R7VM0/9LdJREOhABKbTNqvVYX84V6hZ5snJJApzsNit3Z75I5V3
jpTaBQk4qR8jnFmKPpg8yR9ac30Sq5N6D13UsTcJPSHzseJJKtt3rQrAM4EvLuBmLuyailPp974xiSIK
e/5X7YdUVzM6M+5+InTsc1HLHJrt+gt62yvUDMbSt9MRgICSaSG2RKlK+Y3+kPPNGXW+R2FAjBo0JAwE
i96iyzEXJVCuyYEHqQNnC06QygQmT3lMnuARSTJrmtxZJ3fvvZtrQuaF4jAi2a9V5HEh82avYZY5hM6y
+xsIaqzVZM7lC/6AWIGKZVDRsGb+BdSSPpc1pUHmpPPeu96aRVb6dxMClkKFFixHKQgnXWaOF9+h63yP
3gY/MWJL2EjmtNShnIiCL8fit3KTWiOBck1eBBaMMh9LHajLODhujbunzFDua3KHndq9tyz0OBgFkdan
Isf8cszmJDir6Ss3UscKS94vAgM1i4eMB2uz4bpyktaY+y3cmE6DZc6YBK6X99a11jSuskEXI8AJblRp
sOS9Lxh2PglC5+Q2KhvME6//7YwXr4P7/UT8diTThtikbqgbYeBe0zcIqenym6CB8Y0ZHpHU++rMjr1j
MdXI3HsTRCAuR465kHnz1yyKUuT6wnLpn4PK5CENZE7X4ZAuxALLvHhNTObMsRUybx5n2aK7EIjIu+Rh
Dmx/IjNW3AiLPFD4W4s14W+HpI4Gl/FJIPNNKq8t9UiQqbvwaNHZAD9mz0wii2Yg93XE7rxVe0ToAWHq
bA+07j/JurQps+C9zejPfQlBXBxazpp7Z0Kz9Is5qjBVKt3rqwePUUNPKteCfJLgHnwH3F3fx43oJWqn
rAMuHXLZQ5chwILoAdbJLcP1Pl0dds7W51cXc9JgqRfcy9D3DdpSNxDVDXu+y/Bo1elEHpFB2wjL7ruC
4fzFissc56+LikK16lvbYL9dfoFgVlYAaWP2axbcdxmD9j9Clz3ED4M/LCHztBcgA+BoLRTdO/1H/v1F
Kkm7QTpazaWFtBzr124cqVvCYpboLKeFV/r1FAKkZR9EnVFu6cv+kP12ffb1pF73HHEoX1H53BmydNX0
NVK/zHEOljk+pSdL6zGhYqXHLm3dS+i0zJkDTTIfd881cvYnkO/JQWYTMo9wSPN3CjefPgTr3Iqbz3H6
x5BY5EkkKQQyrNDbAtWr5yM1jbm0UjQhDbLSp1cRAKFgMpyHfkPRuxzBcK/XQNSto2tXfBxcikyRzyFT
5J06uFTiUZq5ZqL7fc6Gfo/7gWAk/5FuJ/XuJLYogtSILHPvPK5bCZk38zuI+0aWeR9uOjfqCFzObOm6
omWekPl1Ox+FX8u9iHoHmdMyFzJfBNKySW8hAEMKaVUMesvbp8EK36xPv24dXWeK0FLHvQyu+XcZRe8i
bdVHS4Vda2Eu82VAfjNw7/eNvHOhjl0gxoxdiDhimb9u9XfXfYTOgeKAIegEcq4fNnK5C0E0zDFn677z
jc6rFX8rOn2m6F7jjziv1F9AC2L0mKrWvtcpaqUnWFPmT7CUsR9+NOJmb8UoyD67GYGsjjVxcq9F7MlN
+kRJOAwwZaOFvnGjDpyrjjjnGq57IUidgXOwPKPUUN1P/syHAL3QJrwbfph3PpQZcz8W4QqOGB3tOj7o
Lpc7Z7TnR6kgcFN9HG6q93Eg9YBypiZtYQQwd8V/cAdyzdy7Epb5qXqjxB0YF7JRhUf2tULrTtR2fizK
QQqZL4ys9BAE5kIgWtbyvC3+XvaxtchsesLYEo8jjBREbn8AqosXiOriXFDO+X4Uu2DbGXg7PoMJ0ns1
rjrToHsmR91DcjqQhMFuRggy/yzI/O+EzOe8uOf6gK48H2SeQQDc15A+c7ruyJxZptnEZN5XcP/aD9Xt
0HDfQ9eLl6p0c+Ep7wsCaRGoyyLJIYvEKNcCTrkHkvp0TNDZiAm6CF4x/l75r+ssTZ5yC9r0/W2n+wV/
JH+W/o66IMQWfOeK7rI7CD0hHEBHdTLl5N4hASRNX0fRxc7oW6/0BQTARRd7gi1LoUKjPbvpkYMD0/qx
1ItvGl/ZQBBYCAEqMELnwfvXwKscrd64x8O1WBVuGS0nUomxao4VzzRyzueRtUNKp6yykPpC6EafT9/n
3NIlEJ95q347uc+l20fb9ur8i6BuIEDmlyJyNCJzETRp5qLjRc782IzheRdFZA6LgDNXWuasFAUyZ4lZ
kPk21CJGvfgJugOnK0g1823SVxAQBGZDoI+xKIhJeW4ml71XXVfcu0HCVAelwoOGLBNEbH9BlYtvgaQs
7HNWJsH70tIggPgqiF25JQQk5s5A7MLX9Ua8z5FLOrx19gk0kLn7TQzQ6TpylKkdIsKQ9tLEhYz/bIpd
uBegrvC5UcoMg3FiMkeJWQtV6ULDlBKzaVGVfoLA4hAAqZemwkH7GVbF3KEKDz5Zk3qt/CoyTeIsE394
zVfVlHeayg5gpdFgsJyQehrMyQ1YmY2zDP4WpP4tvZleVixotb40u2nHPp3rck+CtIAqBuRKrPu+LiZz
sRrTX2lRnqZtm7DM34/0mI/Fs1Rc8rhx1ORyUcjG6h9DERvY8VKVLj280lMQWCwC9aWJg6PUyJpfIoda
L3vV9pgUmtpcWq/MTEGh+rMuUhLlqte6yZN5EGBqLovh7PTGkM2zQfes45Z5tmzLjzrTQi9gFsX0DjQU
ARkTMl/EtcV1NwbTDFJ0wXuPJnNeyFyRI5lTPAaKcNamndS+H1M+JKWFzBcBtGwiCCwKgT5IVFcQePoY
yzC2913jPpfLXjowNdkdU0dhufvrc5vx+zxBJ/JYGQu/3yg6Puknj3MjYGDZkHoAa+wRlK+dqQcw95Zt
+UnnEbqePQ1FZM4BWGMPq6IWNBHLPP0lxqpEJlLOVDhZeitkET+rCXxIkzzyXyPxGHO89E5l57+mix2w
6IHM/NMjLD0FgSUhwLAWkM0k1nqzg7v5gXF39prSwWpof5B6nawylsNI8oh7+Q4UZY9XPrjczDCPXUg9
Pf4gdXAI9QAKxW/rzepFftLvZ9V7dpbLvc4VooF3nBMiMq+7wFcd0rY/AJC5aalsP37y5df7653La+kx
iSgP1s4RRQuFPedCSY1p+/GUA+x+BKr4vWZUdbIK59mx1fX5LUkKae3UucYOcs8UykfD+XarsrLoP0VS
j0Rqah3lydwIwAOSz0HmunQjJkjTYlqxN3ju7drnk84h9LpcQZTnvAH1gl8FV4lIjTZ3LfnKtCz8A5lX
h/3hXKGWFkN8p0V5Poo8/n/AhQ2rHNHukufaHMrSWxBYfgSqmqS5Th6qlyPd6nu1327yXfEae6aw81DE
C/8Yk4ABVZmUmuoJPukek9oV34Oo1sv1JnXB1+l2sXq9OsPl3kDm3nVC5ou4YAy44Li+xjY1cUIDmfOC
ZUQ7pv9I/bs4InMq7Ok0js64RhYBiWwiCHQQAhkEvVXhXYPNnbkJHsrXNqS08UTiNfbq0Jq7zdA4XE1N
etCL4FKk1FRPP9AsREVSfxnis76nN2P0OzmoA1pHHKTaDyu+aAD4a2pN7kSxzJu+suLZvR8avn+8v2HN
d7TLTuuxIxCOFyzxHXe/AZfTWbEoD6+NzvHgNA2JbCAIdBgCIQJVGZjKRJNsbjPuh6dpUmcAa+RJA6lz
jf2+vsqI/U/I3T0Ek/eHEFgnpN7cUEekvpv9Up1BxW3Pb24Hq9W7/QmdqRlYw8Ca7lmIZn+TLmYgFb2a
uV6qEILBelqlYoTmOmgY3xKlv+jgmulsgXF3HPi+MU79oyUvZN4MytJXEFgZBMDTyB+dKitkqHzLLHhv
03npo9Te0MtjNVKfGsn/3LcyByOw7gFN6kzRkpYWgT61k4Fy9utQfvvd2ughF7V5a++bNqOtUd0rW3AP
gD/4ZxrLMIzSrdoc2DY5PETIwuVWmSybQfWYyobd7q0F03BWHxd/QLrGjYjwfLmeLDGNQ5ogIAi0NwKJ
3GsOmSol72xkqnx6Rq3vpMTxpoeeYpnZrchqeQKkYiuYqstvPN3oMtUA+UCmMqvh8yob7J/pDCBWnGzT
1r6Eztkm86HRrIK7AxKHB6GqF2aY7T9LapOxrqi+wSxm8jvNUB1VGXH+pSZMkZA5Hq0HvB9CJW6dXjcS
z0ebDJ0chiCQCoGaMFRYKp0fDNkfrq31MiaGLamOuMl7vGmG2yAr+xSQugQTp4JXd6piIpQBZj+B8MwL
9Dt13JR+NyvTs31d7pdG6RbmWOksEA7IHDNLIfO0VwUFKUjm/2f5wcERmd8XqUxx1k7L/PI/2tYDpW0o
BiFknhZV6ScItBcCUZyL5/koqboRVSY/oYNbma2SBHFxTZ2/+Q32/wRGuNYoe79kARgYniR1aQsjkNHc
k7cPMseL79DdY25aeNOV79GeFnoyAyo8uJsV9v1SZbJ7Yw1YXO1prg+ukw1CynDC+1/fsA5XQ4O/q83S
ExfcVeEeZsa7w7Dt56CusszW0+AqfQSB9kWAnkwWV0LREfeLKHt8pj7U+nSr5Ld/fbi7OeXdifKrz2Eh
GPQDuUtbAIEAcUim8qf+1y+Wn6netFdRxyvEHuQFtl3Rj9vTQt+CAA80M+x7Oy5SkjmDOdrzWFd0uBb8
MpZfzMI99J++Yb6ggczpemNU+7Xe46xMaQdcb0LmC8IpHQSBjkCAhpkZVRBz3oHo98v0UetiI1rOWdVS
3E40Hg52tw9BAZifwvNJMhdLfeEhNiHSUwFejzPXDL5Fd7/0p20p2NN+FnpinV/8q37rMY//BcQRnqoq
EyI7uuBFBxdaLtdneO6vqqaCZZ5/oCY8kayjXfvw06xq5k6sCT1egmMWBFQ6CAIdhoCO4UJZUEzqi24B
lvqwPoE6hc2aKuT3wn7LLf1Y2bnDJH4m1TD7yOm3wsnyr4LHOPvpZcuEq1JtvjKd2s/qja1zkPlL1WBO
yDzddaDJHNGu/6/aX13bSOas0IR1tKuL+1t+ZjvW1oXM02EqvQSBDkNA22eRLnneGUIO9Y36BChdqnPV
8YrxM3z+MmPSV7mjsOS2BV5QsdQXHmkLOf2+Meg8HbFHx+vuMVctvOnK9Wg/Qq+dezgUOdnjaM3a+/Jk
FwSmtOsMUZjBpHuoOnGPh6OypyzaEJVbzF7jHWRZxr1IYXuULvYgaSu7QCgvBYFuQgC/e11sxH45SP1H
uiRyQuQ8TT5nSjCI3h9yjoGFfrMmdclTX+AiABdxMTgAN7Vpay+Xe+LC+PoDecsZ/HcEIjwOaxcSDDf3
xRPrDrvbfMN5oZZ+TFLSYjd7plA8GrD+EEsXyEfHOpBkCsyNpnwiCHQVAliGc1hsxL3H3xvEfYwxUXO5
8zzrXPG1Ylc7JU99nksgUFkEx1Wmfu8/vPNZ6ozHl9otOK69LPSNW3QwXCbXfwAIiGTORaH2OsZ5RnuF
P4rIvOj9yP+Fc1QDmbPyEtzs1mbvpSBzOIayFJdhVQcRlFjhQZKvEwRWDwFY6tQlt51DzD97d6sr/7JG
W+eMeGejK56kjuYP5V/NdXeUo+ZnFJ/hvVdaIwIk8xD30ydld7Ofqz/a3F781F5kefQ6jVFgmgcpqJWi
MRhO2q4I0DWWx7qXW7oJYgcv1rmn/GHSlcYfK8ooWmPF9aiL/D38g4sIRR2kjOKuKMprQaAXEOhTXmkK
aWoHZLJ921WhuFct4p1nr0m9EJE6g+iK3uU6qC7EvURIfbbrw1cDfco3swfpD/cCSm3U2ovQH4hmhUDo
OW2EUXsdCsmcs+iiey1KKL5CH1ziOqO7HalpUNZ7A4LfCrqIQ1D14RZqyxSL9gJWjkYQ6FYEYKkj5zwc
dJ5pBcYOdW3piZrUuSzHNjQ0bakPO6/HveWrKNKURb0XGgJiqWuQGv8YoR9Z6DFnNX66eq/ai9Dvjy8e
Q/0VZBKkNSKAHxYC3TSZe1ciJeW1+uMCZtdDQCu20M1C8UzI5F6mizeEoaT7NWIorwSBXkWgT5VRbGTQ
3seqBjtUYWLfpDKbBoSWeqwuh3vLWxBU93msv2dhf/IeIqRef9VE3LSvfivhrPrPV/F5G7kLWCkI2u2j
o2bm2Wf/POwffLaaLAsh8eKg6yvEDysPTeGi+zX84E7X1wyVoKIfG3XvA1QFeh9cax/HbJz9Q2zXXhM2
fdDyRxAQBFYRgUgWerL0kB+GRylUZKspSfKgSOqUjoUKWqbgfjK07XOwDs/7MO8lbcQXPNhVaT68n8hH
L92Pgjj0JGOyE3PXqhxO45e2zw0/mQMe+A4bV5OjAkyDSEnSiIyPtBKQeenzNTLnD29jDA7IPDNWvBBS
riDzUjSjFjKXK0cQEARmIGBkdepq38AelmHckx3zoCipSylH7ncWddmI+y7uL9Uh59zQdS9AWizW2HX6
sPhNyUmoXgtiysMramt4E+6agfXKv9E+hJ6cu9+PCyscQM1fmQ/q2R/c6badMVzvk1gzf6dOk2B6Hxt/
fJxJjxX/Mcw750EkAmSurfb2G9dkfOVREBAEVhEBzT4o3DRRRSaRjYIt2zLjxShLhtkxbLyv0EqHBzAY
zn8o9Lz3Q1GOgXO87/Q2qROBiJv6VbnYj1dt1drvxj+hLxqJr+QPh25zzI4xSx6tDjvvS9a41ObNpv7R
4VKyxr2vgszfBbcYA1g4nhHZt9VlJgcjCAgCbYZARqeyZrJZGJ23w73+EmbHaPc7DzQqPBIyNgeu5Y+B
1N+D9XfeW4TUOScKca9lhEGbtfYj9AynP3Axtx1UKzhyoZ4FGyBzM3S9czFL3qiD3kZxGTHvkVGpaFCB
uhrRqG8GmTNvNJlBr+CBylcJAoJAByOQUT5SWpHaGpqZ7yPV9STtfk/y1EnqDLhF9gxI/bNh2X0b6kDg
zmyQN/Q9qIPPffGHbmhyqsJSbzsM2o/Q1SSr/0zqa6aN1iYWP/pNbkky5/o3ZsNhyT0zGHEuSmQaVYFk
jmhUNFjm30GQ3AbkjUbqbxJv0CTQ0l0QEAR0SitTWxmz1Dd4LYyEU3RKG1NgdQOpHwPy1qSe/wrKMr8B
RUpowdOAaDtCa/2IAo+I0CdUdreJ1n9fc9/QPoSeWORDe7vwt7vKZBwGLNLear4yMfvtH1RIMXkTLPMv
aqnG0WOiggo6teS2jNZndnKvBJlz8oN1rwS83gJLzlYQEASWBQFLW5vVSYWU1yvM/8/eewBaVV3p4+vc
9jrv0YuC9A4ioKKooEbNqBmNCUVTJmWS/EydlMlMZkzU/FNmkmgmZTJqjCUmRsGKGgsWUBRRQUDpvUhH
HvDqbef/ffvc/bjv8t7j1fvuvW9tve+0fXb5zuF8e6291toPHf+KCVJFUjf2OiR1L2hVbE7x/VJTNRfR
0jDBx490VyN1UBI1GiJHIVxVG/S96Yl2eRBtLSRzCN24rBmDLoK1H8TGvnUlQgeZ+/2IXw/9RPUNMIC7
x0R9s4sqcDvPLfCPOec1WLxfgihxJHPPMrWtb4HerwgoAl0dAZA6pjvDla5TWHwHXGC/bUicU3zWCBdB
q/hNil1f8rDEItcYkx1/wA95gvY7XSUh9KsRoT4wHaa3UQaljGqMjE2Imo5vE16jrpP4D4L/MJjC4Wsx
Cv5b3VrmnM8imT9+pMwnlW/C2nSaic8siP6kSRFQBBSB9kMA5I3/qivjcIG9PfBw5U2JKT7oShOeNSR1
WMPHZhctwGfrCszBwzwsSPV81yF1cBPEzY0G9hmZxVSZRZuJuLhuPL6q/d7RjC8JZI5/EPiHgcUMr4jN
LXrSWJom/uGY+awnK/oGIsG3nAIsCFBp1OxK5hn/WLWBikBWIuBxAlxg3eLC/y/wcMXPMGfsuapZaTRh
DR+dVfwCmH4mpPUoNIsgdZB9rifOnwMNDG8ykqMyi9ATcXH9Pt8yqYa9AS23c3senb6gAYlGIo7PPyM6
t/iFuqhN9AnlP5y/VQ/212BMnFc0AkFjVM2e6x8M7Z8i0PkIkBegEKyKuiVFPwCp/8a4sdE/3YtOifjv
DEazJhSdU/KqLx67AN+warNEcy5L6uQiF3YFVZUSi7vvmMeksdybeFtnGXctifQuXAVpdZME8hGVJ2fn
0SOwFoUvaLjS58amR2cVvIY58lBd1CaS+UPHx/h9sbdhqHI6DFFA5qpmb+Lt0UuKgCLQfghQze6H4S1J
/Zv+hyruNkVTWue6EUwJUo9cX7rM57jnS6T6GCzlqX7PTUmdHkihAkrna2V98VoPA4+zzH4G/MksCZ3W
gne+480ZO+6zkmesD3LRNcKLpxyuLvc77nmRuaVYLAErH812zKiXW4RknOz3OcvwAvWSWrqmqQFcBvx7
0SYoAl0JAawRAS0pXWO7FX0R3jV/M503S66mkPrs4pUxf+hckPphxDpnxLlcJHUQuk98rrxgAnuRq2jM
nUEpswidwHSfYuZrHL//Qammhlk44sso0NioVicuf5qH5U9rqw5gcYRzw7OL36tTsxtSHxcO/O3YhXGf
vCGBvBKEaOQ/DLw4uQNBq7HTGxUBRSC9CHjxLYJyDKReXDQX8S+eNA1IuNB6+576XT6Ztx7T6edIuGov
AtBg+dUcInVv6jcg/BzH4/NNvxNcld4H0nRtGejADIUGuQvSOl6e1yS/8AIEM6AFJYk92xOXL+Qyhrti
Tu0FMrvHzpPI/OGKK9D9Z2FkAiPScK70O9ufm7ZfEVAESNAlIOqKyhdj64quMFIqfdXphcNk7X7mVZ3m
d90lUlA4GBbzuWH346CPeYUg9Mq34IV0rukvLf8zyAedbco8CZ0qjEUmjCmE0vhvM7GF5mG2+A/U6YWG
zDfHHPccQ+Z0SeM8VGLL0IuuP/AcXNiwCjEsR3NjENNipPQGRUARyEAEHGgKK0DQxUUf8Y+pelV+uynP
kDlJnYl2P+ZbVvhBzCk8x6mu3Gi+ebkgqbsQs2g54MjvTV/Z5wwjc7YrAyV0A1fdH8zbvAMV9RTMI3Mu
3TPGqLuaNTuGzN3KijVxXxwrG5V+eMLPHPMwX5kagdHJZ2Ekdz+kcg5ksrmvWfNQtKGKgCLQKgTCWGci
hAVbVsQrqmfKF3sfr/uesTiSOt1u57mlPrfyNaewaAIsw7NZUo/BlsnvhKvWYknZ8R6RQzrPsPlzQp+B
EjqbhWRHfY5zc+YPO7wmN/LXvPxQPb0TD0NVY8icJM4Xfp6fZO6bd/xGqOJB5gi9qGTeCIx6WhFQBDIE
gRDjYYCoJ/uKC5bJg8d6me8ZiZyJ3zYajM12jsZri84DmS/nAABXjFGUyZNNfzgJ7EfMHcd/kyFzw02Z
ZQxn4cxsCZ3uETC+8M+rfFQKC69LrCrmvTS2B5m9pXoqhDCtS6CCutRYsfNl4JwTgzTArxMhFr+Hfxi/
xEvPGE00QcncQVZmY62tUwQUgfQiYG2CtsXicoFcX7Snbh6d7bDfOrjj+qXqJUS5vMCLcplFHjucLiiG
3UBl1QKE477GCGGJ1S7TC3Xzasts8phlzOMkliffwIjwmAQCJPNscWNLkHnlwtjsQqjZMYduX/BbQOok
83lV33FKDJmzT0rmzXtnNZcioAhkBgIhCCIRGC4P8fsQaOXRmqHePDrduZAouPCbh29fbG3hDJD5QiPg
ZI+kHhOsF0/uwYDlxsyAvOlWZDahM4gB1TjXYOTn+L4oeXlebzw7+KZ71rlXaQ0akuMVT8Ii8nKjprnl
lRPWoDMS3XDjlyfCEpDQM/tZdC6eWrsioAhkIgI0lKsGqecV9ffHom/JI8dGcxqxLviM0Ubi2wcBxnwL
K6q47DPV75nup258rSTIpsb/yWgfjMHf7IwWKDOfRDgfg1EepNxHnKrK/0aAA6wKlLEvA18Cz7XjeOVf
Y3NLrjX/Bjl1wCVQT0pOReJU5j+Hk9quJxQBRUARAAIkdQa/Chb09Md8r8u88iGcKjXTigSI375EdDmj
tj5e+ZBxf+O3MjOFM37Ho2ijz62p+mFsTrcn6gz92J8MTtlBJAj/D420E51T/O8IcMCXIRMNLPgSxMyL
WlF1F0ajnzbPPWEH0PA7EE9Y7WemgUXDbdazioAioAikIOA4QQlX10Lg6uGPB843V/sneSUlRZfDt/F6
qN//ZL6VrplC5bczM5I3wIiiHwimU/F/8TlFPzEDk69kx2py2UHo9Pe7xbN1916GiicBeCghqWfCy8Do
dnHMDwWcisrbsbTgV8zbyYUM+CJrUgQUAUUglxGgnzbdipMV6SM9G6i6bvNbmFjcJTa7+J+d45W/BanT
h937ftZl7LQdtsMTyo5DKJtb8lXTkpvZj+wQurKD0IkqV/qhmxdSbDZU2ccq/yylGEXRmIwPobMSIwhR
6VRU5Hcrq26Gn+J38dI6ZlRnlx3srLZpvYqAIqAIpBMBMorPyW+0Sn4T6eGDbyQ0rt9yjlX8lN/ORP7O
+45Txe44PgTCCWCg8d91QhnbmoEBZBrDN3sInT2gu4Ad4c0p/if3WMUP4fDvQ0AWvhD0cUyftO6pZsJm
HeC8QsetqvhGfHbRj+2gwwxA2GZNioAioAh0IQTcuCSslxvpNIWzW281Qk90bslNCFDzPcTh8GH5Ve87
nt55dUrfYRj1edHuKqq+ZKZ2rVDGtmZRyi5CJ7B2hIeRU3xOyU+ccPVlUluzIzGvTr96Kn06ktj5AkRM
DZzLj9budsKVl8Znl/weI8+AzJoVz6YRHSHVpAgoAopAuyHguE0TOiu65Za4UJUNG6P4nOLbECb2oxKp
3WO+497XOw3fcXKF40hJYcitrVzni8uU2Nyiu42rnWljdpE5m5x9hG6B5sgJ0YgwmnoxVlQ0FmqS/8El
1wQBcPCQDLG36/w1R2q0yhQEuQmKz+fI8ao/xPKKxkZnl7xsXoJboH7PIvUMeqJJEVAEFIH2RcA5hYRu
a+O3kvPq8GLCd/z5mBMeK8eq/k98fk5hcjrVCmjtKSUnvuPgCK+OGLjj53GnaEJkbtEKY81OV7ss/Y5n
J6HbF4L+jgxc8DGnCi/Et2MxdwKCADwAtXzUEHvIqHDwACFRc46EC9Q3T3rnGJF5OafDOXIGGPB5gwW8
bFWVz/jc8FS4YHxNrnGOmzbwJdCkCCgCikAXR8DnOqeW0JMx4rfThIrtcRQS8ld9sfgUqah4jMKz+eYG
sAi5/RbTZqkl33Hm5T0eB8Sg1ve+4y4mBioqH4w5sXHgjv+wAwsTtja5bVm2780bZFmj6zWXLwPnO7hC
28XOGjDwZ+WhYz8JHMdiJ44zyw2ERko+yNhQM54rFz+J42F68zT1VfMcD3rr//pB4A7mx731zkjVNZX7
pCL8pM/x/TEyp3i5sd7gYGIxXhi2QZMioAgoAl0dAX5DpZkSejJWFM5ogDZDfJGLnRW49IngQxVnxo9X
fBnf8WuwdOlpgk+yEa+ikM/4HSfJU5L2LOxxSEt0cAEHAuQEWt0HsQw1hTEyXQQyWrh6hxOpfSTqD97N
9dtx1gtRO9OUlfXf8ewndD4QTz3iBS9YC6qe62zEk7kJ8zM3B6LHp0lF5CN46tORcyyu9oUBRsBMNvCR
88dEardyeW01Hn74EF6azZiVeBtXFsYitYvl0z2PGSJPBElQIidwmhQBRUARSEKgOXPoSdnrdj0DNHgz
IRAXUmS2swqbr8m8A/8WCMt5EvZdhu/4eSDrETjfV/JhHU/ZvbHveE0lKD98AL8NTo0sRc6F0aqDS+Tz
Q2qwj3n8VwIydqabS9/x3CB083Twx/p884XojccMyRnE/jqu8Cfy531FUth9YKC2ZgAWNeuPl6M7BgP5
nlTuVjs+pwJjvL0Y4O2P+OI7zcpo5sbEH0rkB5Hb1pN8TfcVAUVAEVAEKBy3TOWeipn9vp74jlfgO74Q
2fgTufdImeQFBwVqK/tCOB8ApWoxpLECXAG9+2ociR/FzPx+HOwJF0R2yse7l5v77J8T33EUm1sptwjd
Phv7QlD9Mg8PmeRO1fhnHQzZZD2eoqdqsfmb2vLhM+WISqapruo1RUARUATaAYG2EbptgP2O2ylVnve+
wyTo8maz8cn3N/tW25Rs2eYmodehTytKM3uOMyB3Ptj58zFwmyWG5Dcuh7JmSiL3cpGRU1xZvAiKeahh
1kISvwU/nR+vQ1N3FAFFQBE4JQJuwm1t8SlzNi+DnVI1ufEN51w7J0/XLnJkxkyvjI04NqmB77ixl+oa
dk45TujeI/b+gty9R26mwZOv6L4ioAgoAopAOyDgmRlzrQ1aLHlH7VDsiSLwHaegpalBBCCtalIEFAFF
QBFQBNoBAVKt43qELvPboUAtoiUIKKG3BC3NqwgoAoqAInAKBByP0NfOUkn6FEi192Ul9PZGVMtTBBQB
RaArIsApTY/CPUK/mUeY89aUNgSU0NMGtVakCCgCikAuI1DH3QmVey73NTP7poSemc9FW6UIKAKKQHYh
QC8iI6EnrNxNFLfs6kK2t1YJPdufoLZfEVAEFIFMQQCRXuBOpBJ6Jz0PJfROAl6rVQQUAUUg5xBgXHWu
tkZpXVPaEVBCTzvkWqEioAgoArmKgMv4qyG5dZGJx56rvczUfimhZ+qT0XYpAoqAIpBtCFDlzljuY2cq
t3TCs1PQOwF0rVIRUAQUgZxDgLE4jcrdDUqBWbA057qY6R1SQs/0J6TtUwQUAUUgmxBwQebRcs8w7lYb
Yz2bOpC9bVVCz95npy1XBBQBRSBzEDCBZei3hhUqI4Fg5jSs67RECb3rPGvtqSKgCCgCHYyAcUTHol9+
dV3rYKQbKl4JvSFU9JwioAgoAopAyxEwc+g+vwQdT0K/ueVF6B2tR0AJvfXY6Z2KgCKgCCgCJxDwjOJc
N5BXG1EJ/QQuadtTQk8b1FqRIqAIKAK5jgBU7jCKq4sWN1+N4tL5xDHXoUkRUAQUAUVAEWgHBKhy9zk+
15dQubdDkVpE8xFQCb35WGlORUARUAQUgcYQ8IK9IlQc5MRIVFXujeHUgeeV0DsQXC1aEVAEFIEug4AX
v90Vf0Bcf0jd1jrhwSuhdwLoWqUioAgoArmHgBHRIaEbWlEJvRMesBJ6J4CuVSoCioAikLMIgNddN55v
+rdWjeLS+ZyV0NOJttalCCgCikBXQMAS+oyu0NnM6aMSeuY8C22JIqAIKALZjwA17w5WXNOUdgSU0NMO
uVaoCCgCikDOIgC/NSQroedsNzOzY0romflctFWKgCKgCGQnApxDd/wqoXfC01NC7wTQtUpFQBFQBHIa
Adf1jOI2Ljem7znd1wzqnBJ6Bj0MbYoioAgoAlmPgJlDl4SEPiXru5NNHVBCz6anpW1VBBQBRSCzEfDm
0CUhoWd2W3OudUroOfdItUOKgCKgCHQiApDQfeLTOfROeARK6J0AulapCCgCikBOIpCQz2EW582h52Qn
M7dTSuiZ+2y0ZYqAIqAIZBcCCRM4LJ+qEnonPDkl9E4AXatUBBQBRSBnEaCU7roeoY/E6uia0oaAEnra
oNaKFAFFQBHIdQQgopPCnYSV++Jc729m9U8JPbOeh7ZGEVAEFIEsRsB1PJk8MYc+ViX0dD5MJfR0oq11
KQKKgCLQJRCwc+jzu0RvM6WTSuiZ8iS0HYqAIqAIZDsCNIpLVrmvnaVz6Gl8pkroaQRbq1IEFAFFIKcR
gHl7QsnuGcXdrCr3dD5vJfR0oq11KQKKgCLQNRBQP/ROeM5K6J0AulapCCgCikDOIuC68FpLWLk7jqrc
0/igldDTCLZWpQgoAopATiNgVO6u+Oxqaznd2czrnBJ65j0TbZEioAgoAtmJgIkUBwnd8QVl3jy/1wm4
smlKCwJK6GmBWStRBBQBRaCLIAB9O0zjAlI5K2h6rEr3tD14JfS0Qa0VKQKKgCLQBRAgobtuUHqIR+hd
oMuZ0kUl9Ex5EtoORUARUARyAQESuoDQaxOEfivkdU1pQUAJPS0wayWKgCKgCHQJBEDeJHQnIFIZ6hI9
zqBOKqFn0MPQpigCioAikPUI2Dn0WK2q3NP8MJXQ0wy4VqcIKAKKQE4jYObQoW4P+T1CHztfVe5peuBK
6GkCWqtRBBQBRaBrIACVuwOVeyw/IaHP6hrdzoBeKqFnwEPQJigCioAikBMIUBY3RnESCMUdVbmn+aEq
oacZcK1OEVAEFIGcRYCR4mgV5w/gT1SN4tL8oJXQ0wy4VqcIKAKKQI4jAFr3i+uLeSuurV2kc+hpeuBK
6GkCWqtRBBQBRaDLIOCAw52gR+gys8t0u7M7qoTe2U9A61cEFAFFINcQIKG7MW8J1Rm51rnM7Y8SeuY+
G22ZIqAIKAJZiACWTAWhu25c10RP89NTQk8z4FqdIqAIKAK5jQDd1tBDx0mo3HO7t5nUOyX0THoa2hZF
QBFQBHIFAV0TPe1PUgk97ZBrhYqAIqAI5DgCRkL3q4Se5seshJ5mwLU6RUARUARyHAHjja5z6Ol/ykro
6cdca1QEFAFFILcR0Dn0Tnm+SuidArtWqggoAopAriJAK3f0zU0YxW1cziNNaUBACT0NIGsVioAioAh0
OQSs29rIKVwgXVMaEFBCT/WAheEAAEAASURBVAPIWoUioAgoAl0KAVC4T93W0v7IldDTDrlWqAgoAopA
LiPgGhU79O6elfviXO5rZvUtkFnN0dYoAopAuhBALC/xe0td1lUZY4QvMwFad0p3FIGWI2CU7IlIcWPx
SmlKCwJK6GmBWStRBDILAR+IPOb4JBrkktXWZskVXzQsQTcuUVzTpAi0DQGNFNc2/Fp+txJ6yzHTOxSB
rEYgAMKu9YckEAvLhB3vSbdD20T8fjnSe4Ss7TtcaoP5EgCx+5CPpK9JEWgxApTJXdHAMi0Grm03KKG3
DT+9WxHIKgQofdeAsPsePywTXv+jFG28WxxfARbSiEkPf5H0H3qd7Bn/MVnbf5REA/kSjNaKk5Dms6qj
2tgMQMD1FmeZpSr3dD0MJfR0Ia31KAKdjAAl85pggQz+cKeMefG/JHRombg9z5NAwA9CdyUSrpWCHc/K
sK2PSb8Rc0HsV8m6PsMFGSCx10Ji99T0ndwNrT4bEKCEbq3cb82GBudGG5XQc+M5ai8UgUYRoJkbybgW
ZD56zzoZvvBH4tR+KE73cRKrPiYrV62T4uISGTp0qPhKB0s4EpGiLY/JiM2PSv9Rc2X32H+QjX2G4gPt
kxBU8dSlqiq+Ubj1wgkEVOV+Aou07OkEWVpg1koUgc5BgETOFIaafdLWZTLyqRtFolUSKj1Nyg/uER/m
zu+773755je/KZs3b5atmzdIyAfr99KhEi8cKCUbHpTRT3xBLnntbhlxaLuEA0H88ox1vC27c3qmtWYs
ArSxNK9dQuV+s6rc0/WsVEJPF9JajyKQZgSsijwO0j5nzQvS75XvixQPk+LCfNm9e5v0HzBI/uu/fm4k
8/PPP18uuugiWbBggdx7771SVFQoAwcOklhwhEQitVKy5k8yZsM8GTD2Btk15jLZ2mMgeuNCYo+Yr3Uc
7m6aFIH6CPhC9Y/1qKMRUAm9oxHW8hWBTkCA8+URn1/iqPuCt+dL/5e+Kk7paPEFQvLQmnIZP3Gy/OZ/
fm3IvKamRqLRqAwfPly+9a1vycMPPyxXX/0xWblypRzcv1sK8oLilI0UN6+nlK3+g4x7/Cty0Zt/kcHl
eyGthyTiDwrrU4m9Ex50JlbJQAbQDLmOS59IzqVDXveCzWRic3OpTSqh59LT1L4oAkDAuKWBaPPD1XLe
G/dLt/duF+lxjoSjMQnGq2XBP4ucd8OPpFfvvhKurYHHmt/gVlsLwzefT8aOHSsjRoyQK6+8Uh555BH5
85//LCNHjpBevXqDwEeLC4m9+4rbpNu6+TJw/A2ybeRM2V3WTyQek1CMErsjKrF38VcRhO6Lu6G46/pA
6BxXakoDAiqhpwFkrUIRSBcCdEurxRx3n8pyufBFkO7aO8XtcS6k57BsOxKVW2aXy8c+Wiq9ap6VSHW5
+DC3LriHiWTORGJnmjx5svzoRz+S+fPny8SJZ8rrr78u1cfLpSAf95SNxw1B6fHWT2XSE1+X6e88KqdX
HDZz9RE/rOJVYjcYdt0/lNAlKL/b7EnpnilH14UjTT3Xia80AV2vmlfcgFzsRP0PH39cioqvlcqqCL6q
3otfL6MeKALNR8DzMS+QMz7cJWNf+m+4pb0jbslQfFVrZOkHIvO+fESmTx8scbe7ONEPEGl7tMQGfEXi
RYOM1O0wYlzSXHg8HjfSewBua5WVlbJs2TJ58MEH5bnnnpOJEyZIcUmJ1ETRvki1+Co3SKzbmfLhxLmy
Zfh02V/c00jseZDYNZxs859hTuR0MdMTyvNJpHZnrLZorHzWqYQKHq8XVe+aOhIBJfSORLexspXQG0NG
z7cCARuT3bil7V0vw1+4WXy1h0QK+8JiPSqPbA7LC1+pkcsuPh3f1WIEigELO7RXqgTpgnDLviSRPtPN
eQeStYO5d5von84f1fIk9qNHjxpJ/YEHHpClS5fKhAnjJb+gUGpJ7OEK8VdtkkjZ2XL4zLmydeg0OVDU
QwSknhePKrFbUHN/G5dACHGFw3tjTtEYme0cVUJPz0NXlXt6cNZaFIEOQYCGaByVM1zrmdveglva1yB9
V4ivqJ/4MV++dN0+ef7r3eSyS4bgm1oERRDJnE3Bll5FxzaJf91FEtx6v1G9x6FGj8eihsSZy4HETlU8
pXUazxUVFZm59d///vdy++2345pfVsF4zonVSl5BCQYHZ4kvXC59F31bpi74vrGu7xmuND7wUQeDAg4Y
1IuJ0OZ2wnuJxxyU6HHVPKbxSSuhpxFsrUoRaE8ESOZxBHuJIC77OWtelMF//7LEg90kUFAqsdqjsm73
cfnb/3xXLp/ZH/wNaVwCnkYdxCqQmOXIUkjVG0TyJop/9xcktOZH4qs5LG6gwJB6LBY7idh5jsReVlYm
1113ndxxxx1y8803S1VVlaxZ8x780yMSKiiSWOlkCVTvlQEvf03Ofeo/ZOr6V6QbVPPUInDhF4/Y2xMN
LStzEOCIEYROK/eAzzO8vtUbRmZOG3OzJUrouflctVc5jAAnIkmIdEuL4dt5wTvzQZw3Sqx4pOTnhaTq
6EE5crRKHvzjr+XCyz4h0X7/Im5oPKTonTBkg1QOFbiUvwGS34SPbgm+vVDPh84Sp/yXElo9V/xH1sKi
oxDnMWAAgccgnVPtzmQldrq5kdj79OkjN9xwg/zpT3+Sb3/723Lw4EHZvGmThPzQuuaXShTqd//xbXLa
wq/I+c/8SKZuWiLdEG2OxE5LeJXYDaw59gfz5eZ9cYIYWaqEnsana5RvaaxPqyICOoeu70EbECAJcrW0
wkiNnLP0fildfRuI8xwp9EdkV3lUevXoKbf95AcyctRoBIWJiIPobk60RnwHnhXn4P+KHAeRu4zKWYUf
iZqfAZC80xdk/545FR3yvEQGXAohK+ZJ84lV10jo/NlEVTxTKOTFENm2bZs888wzJjhNAPWeccZAGOFB
i4BifGGEm63eLrUDr5F9E66TDQMnSnWooG7JVoaT9YYNtnTdZikCmAfygdTjkZjjHyWzC7bJLXgJblH3
tY5+niqhdzTCWr4i0I4IWLe0XnA5m/7SbVK25g8S7T5Nivw1svFoSC7st1Lu+tlXPTLHYis+fFcdSuS+
PFi0f1yifX8Cwgb5xiid90bLSM4kZQhS7gEsozoSvyES2HKFhDbfZYzmxA/yh8RFKZ0Ezl+yxE6CD4fD
5jdkyBD56le/aqzhP/GJ66CGXyv79+2RfBTvL+gh0dKzJHTwXTnj2S/Ihc/9FPP+y00YWdoAWM3DieFC
OwKnRaUPAT5ADDqRguJzPJV7+mrv0jXpv53OePwqoXcG6llfZ51b2pHdWC3tvyXv0NsSZShXX5W8czAg
/zTxuHzvekcK+k0CyX8Wi69MACFDNAZVUgPqkogh2TtVeyWw6X/EOfILiNajzHVxj2LLby/zg8CdUsyv
rxa39OsSHv7v4hb0xv00ZT/xybCSut3ioiF7Hufl5RntwNq1a+Wxxx6Tv/71rwglOxAq+t4SQTFRfO99
tQewSMx+qRoyS/ZPuEbeHzBG4giI44dK3g9C0AVgiGg2poTWB8aUsLmYIHNL3scLqAFm0vAoT/zrTENl
WkUCASV0fRVagAD/kZLgaqGeHrV3g3FL84MM4/l9pdBXI2/sC8i3zi2Xb84pkFB3LKpCv3D3mMR7fVnc
vh/BtxTaTyx/ytXSXBI8JW64q/l3LRD/zlkeR/sngvH3s6ZEy8i4g2A+/5bES78t4fE/q5PKbdOTpXQb
lMZeoxTPcyT26upqWb16tQlQw7Cyo0aNkh7duyNyHVZtw7ffX7MPGv8jUjmMS7ZeLeuwFrvLcLIgdp8S
u4U0u7Z0ZfAFHF88NjUyu2i5zHP9cF/jaFFTByKgKvcOBFeLVgTaioBxS4N4TSOyiVvflpELvib+yHF4
nIHMA1F5YU9AbppZLt+5oQRkPgTG6zEQKQzf/H3Fd/gO8W36X3FrymG5TrU5SJpz4XAxI4vHBn9SouPf
gwb+ShDqapxC+FbhXDi/uxhGxI94/E6r+LrZbUpfXrKSOYk92SKeV0nmPE8y5/4555wjt9xyi5HUR44c
KW++9ZbUVFdIAdyVpbCfxErGSBHWYh++4PNy6cu/kzHwp6c1PFd2IwYc0GjKIgSMkI53IBbDi6cpXQgo
oacLaa1HEWghAiQyqp0jUEOfs/ZFGQK3NAnBKj1ULPm+iLy47rD87mM18pVZPcVXAuMz6LExZY4EQqbh
WrhAnF3fkMCqL4jv6BZYrvPbii+tMWrDFoZy8R7jJXLmAxLvDfV7eBWu1+D6APzKwMoICgMedUP9xYV/
Ohga100F2J6cKJWT2LllIuEnE3swGJQLL7xQfv7zn8sf77pL+vbtK2+B2CO11ZhjR/z3wgESxxRC0ZZH
ZcQTn5dLFv+fjDywBW55gSRiZxs0ZQECMIzDu+JzlNDT+LCU0NMItlalCDQHAVIWJVKzWho+itOXPyr9
X/x/cEsbYVZLA73JyxuPyD3fuUQ+fRUmpPO6Q/j249uZIDvaIVXuEjn6MMh/IuapHwepDxf/nldRML+v
+GdvpXWQugvf9cjob0t0+As4D/V3+F1I7OvwWwbSB6f3OA/snCylN94LSuWpxM7cJHaep8ReUFAgl112
mdx2223ym9/8RgoLC2XFihUYh4RB7MiHULTxwkHeWuyPf1Eufu2PMhxrsUdgNc/V3fxGYldib/wpZMAV
Ph5qg5wEoa9tYiSYAc3NlSY0PtzOlR5mYj90Dj0Tn0rGtMkYv8F4LR9ke97SB+CW9itYh59twrhSAn7/
/fflrj/eLZdccom45XAz23cv3NJ2wqbtNPQBX9KKrfgtBIv2wTEY2emO0zB6i+yR+Gn3SHTo9bhGS/ew
+ei6CXW2688X3/Ht4v/wHRjObQeTV0q87HxYxl9kyrVz5jioS6c6Rynd/uxNlvQZSpZS+4EDB2Tx4sVm
VbfNW7bImNGjTZjZMBQNNOTzV26FsVyZHB93vewc/ZGktdjD6K2u7GZxzbBtTPKL/FJddW1sbtGT1lU3
w9qYc81RQu+MR6qE3hmoZ0Wdhswxb9yrqlwmLf6DFG/9m0RKz5R8p1Y+rIjJsSP75Q//+3vMSZ9rAr5A
9BUnfFScfQvEOfqoSPUx/HaAqKE6N0IRRSWqwDGvziAyYcyZl31XoqO+L/GCPsY/naRoEokdEryLMhl8
xsjAkPYZ1pXpVOTdVB6rfufW5mN5/JHUGSt+z5498tJLL8n9998vhw4dMku4UrKvhfEc/eF9lVskHuoj
5eM+JbtGXyLbyzA1gPtDGJgosRtYM+eP40QlvxCr+lTMjV1f8rASenoeDf7lalIEFIFMQMBzS8uXQeV7
Zeqzt8JI7GmQ+SQpBDnvq/TJ4O5V8gDWJieZR6PwLQeZOYi7LsFSiQ/8jMT7/gBW6fAlj0FCdyidWwM3
qstByu5hnEJEuGO3SXDldZDE34dUD6K3yRjMhcWBlTxDw7JsJ4r9dkgkbmoXko3nLMnbqHP9+vWTT3/6
0ybq3I033mgIfvv27ZKH5gchzcdKRmGnRHqsuF0mPP5VufDth2XgsQO6ZGs7PJ92LwLP24wTrcp943IV
Htsd5JMLVEI/GRM9owikFQF+6Rj9rQZuaSP3bZIJT/2r5H24WqJFQ6UIK0+uPxKQGUOq5Ldf3iFjeu2A
ZA5pFW5d9Awy85SM5gbyjfWG1D75FXF7/QyS+EoQ+EFcZ/CYhNU6v7DuB6hsAk69LoH3JyCG+3PIk/St
5T6JnXnr9tsPDkvsnE/nPpMldka1Y4CaQYMGyZe+9CUjqV9//fWyCaFk9+z5wBB7wA/f5pLRmDIImLXY
z+Ra7LAxOA1rsTM4ja7F3n7Pqo0leYofJ54wipvSxuL09uYgoITeHJQ0jyLQQQg4lLLxM25piJo26qmv
wy2tXKL5/aTYXy1rDgfkqpEV8h+z90tx/4skvvcP4t9xBwgbc+Kw/qZxG3mR1OjAb5sBYGLj/l3ioxaB
9Ppj3hxSOEO6Gmkd0ryNCOcbi+t+8W//BxjNoSwavSUIFpk6PDVkOEdi56+2ttYEpRk2bJh87Wtfkwf+
8hezwtt7771nYsXTIt4PA7loN8Snx3RCr6U/kklP/Iuct3KB9MdUBbGMcLlXYENPAU2dhADYxXXoL6kp
XQgooacLaa1HEUhBgGTDBUroljZ13Usy+JkvgW+LsGJaCci8VlYizsvHx4flprkfSlH/KchbBFu2IbBg
f1V8OyCFY9ETl6Ru6BzElVCZw/lX4qfPkOhZr4rb4xaQ/yrkqcR1SutMHAhUYBuCS9pVOA9pnCmx8Q7S
85fETpU7tzZx3twSO1X0Y8eOle9+97vGh/2CCy6Qd999V46WH5FCEjs0FTHYGPhi1dLnte/L5Ce/J9Pe
+7v0qj7uETsGLboAjEU2jVs7jnLjSXM6aay/i1alhN5FH7x2u3MRoOuV55bmk+krHpPT4JbmwgcbEg0C
xsTktd0x+eLF/eWm6yNS1O9MyKFYxMT4kMHYLQjJO7xPfCuHirMTrmZcoZKuapBIPXU5+hahtN4PgWNu
ktjIF3ECbG2k9W7YpY95P+TH/HhgENzWirFv1fKdg0tTxM5V3ZjOOuss+c///E+57777ZMKECfLW229L
RcVxyUfXOQXBJVv9tYexFvu/yDlmLfaF0jNcZYhd12JP83O1g0M7h57m6rtqdUroXfXJa787DQGSeRiS
dR4syWe+fq/0fuPfJVY2FZTrSmHIkYWrPpBbZo+T73xsv+T1PANkDsmcZM5E8kakODm6FoZrvREJ7grx
rf8D9kF6cHUzpM58lNbjcEvDfHvs9EslOmkFpPWbcO86DAbW4PcW9nG53yxj2V53H+/tpMQ5dUrrDUns
vGajzk2bNk1uvfVWYzw3ePBgeeeddzD3XisFiH0jULfHSqdgLfZ90v/lr8s5ibXYS7EyHVXxDNSjEnua
HjCkdITuTUjoy9NUadeuBl8HTYqAIpAuBDhfHoYauLS2Ss6mW9rm+8zSp343LIFgQF56/gm5456HZfY1
HxU5+ILEP3wQnmlUpxfhByk6UoW1zJeCiXfja9kHWvP+4uxBONiK1RIffTOkfEjvmEv31OggdaxY6URq
xS06TaLjfggL90/Dx3wXyjmGc4j73mMcDOSYPzPG9lS1JxvO8diq4O01EjuXa50xY4ZMmjRJ3nzzTbO6
29KlS416vqAgX2pdrLdeNlmCx7eatdh7DbhSDkz8pGwcNEkq8oqNvUEIWgldsrWj33zHI/SRU6wSvqMr
7NLlK6F36cevnU87AlRFgqQmrXhEitf/QiK9rpSgWws+9QkJ6S/znpaPfhRkjsTlTn3FY0T23gOS3gHp
G+pyQ+awVHd64ZiqaPzoilZxp/hXLpLYqL+J2/ss3EyJnvPSqBD1mfjtIO14GRY+wY/NMIlknqGJxE5V
PH/0UyehW4LnORI7o8xdccUVMnXqVHnttdfMPPuqVatlzJgxsIqHsWGgGIvLTJHQkXUy8LkvSu/Tr5ED
Z14n60/nWuyFWIu9Fvh7K7sp47Tni4A3DIBiYaCEhN6eZWtZjSGghN4YMnpeEWhnBGgEF8Fc7+Bj+6Xb
hsexxOmlhswrKytl586dZjWy888/X+LIRxU4TMNEuo3GXPiPRHbPF2frFzDnDWt0H6TqupXR+OEEwQfG
g783iP/9yRIf/JjEz7gGRI68XAudhG4lcESfw9GJZM+fOJNxe1YVT0mdPyZL7jSao4q+tLRUrrnmGqE6
ftGiRfLAAw/I1q1bZfhwhLz1xxEsF776eZMl7/C7MuiZp6T3GZ+QfROvlXWnjYcqPt8s2UpVvErs7fX4
scSfeVAJt7XF7VWultMUApmhZ2uqhXpNEcgRBIzfOAipCK5VTvhDGHL5YbsWll69ep0gc1p7g9AdEi2J
GHPgNFpzB39e3DGvgswHQ13OldGgWjdLndKYDZPHxud8EHZHi28rgsas/YWJIOcReZLsacpl2YlfFmFr
DeeaCk7Tu3dvmTNnjtxxxx3yzW9+00Sc27JlqwTQ3ZAP0n6wDPYKkyR//xsy5OnPycULfyETdq4yfgIk
diZd2a0dXworoY81ELdjwVpUQwjgNdekCCgC6UDAiCzg1pBRH8OdCtu9+/bJRRddZKy22QZKo5Q+6xKJ
F1IordDdARdKfPLrMG77TwR+Q+AYErqDFdGMwRyVbZhfpzta/rkIBfsD8W25BwMA5Eni87pys3THzq9T
Km+I2BmchlbxAwYMkM985jNy9913y+c+9znZvXu3+eUF/R6xh3pJDH7sBbtflqFPYWW3F2+XsR+swZKt
jok8x8GXEnsbXxK+dz5XVe5thLEltyuhtwQtzasItAEBL3SWKxVQhbv4xTDP3bNnT6MaXrZsmQmowrli
kla9ZAgeJM958aK+4k78scSHPw3pfTu4fG1CWrd3UMJHPHfwu+NyHh1lJY0PbK5s3VpVO9tv1e3c2mTn
2BlxjuQ+ePBg+fKXvyz33HOPfPzjH5eNGzfKPgyi8rCqWxBGhrG8PhJHSNmiHX+X4U9+zqzFPpprsWMg
FIbEjhW9ldgtuK3a+jSwTKtwa91NSuitw03vUgRajYDDYDD4ztHiPQoy4uIkFRUVsnLlSjl27JiZJz6J
1FmbkdZJ0qDpwVdJ/KytsGr/MlzQIK078CVn4Bj6mJvV1ZAnD+TPe1IHCKaE9P9JJuP2qN1qMkjoJHCq
5G2ylvGMOkdpfuTIkfKNb3xD7r33Xrn00kvNinUfHjki+SFEyyOx52PNd8QBKMZa7COf+IJcuvgOGbl/
M2IF6FrsFtMWbesGkVZCn9+i2zVz6xBQo7jW4aZ3KQItRsB840CuIUSG46IoXLbUB8IlGVEyp0S5atUq
Y6HNefVkgqqrzBI0FmdxS4eIO+m34ts+Q5xdnzLCeJ00Ti19j6l1t3X2jiVftsPuNzhoaUVDWR7LInFz
n1ha4zm7pRqe18aPH29WcaMnwWOPPSZPPPGEDIYU3717d4N/rHAgIHThgfBXGb1hngwY8yn5YOzlsqnX
GWy5hOgSiBRDWZqaQIDqKCqaXPEk9LWzUtROTdyrl1qNgBJ6q6HTGxWBliHgyY+ulCOqW8wJwpQNZ8AL
lDD5y8vLM9s1a9bIkCFDzCIlJCoSuyVBU6MhE0jeXHENwWTiI24Q6TlFnENvwee8HKp4+J13PxsuaqPh
ut65PuaNkTb7wx+vN5anZeh6uVmWJXaSuSV0bnmNxM79KVOmmIHTVVddZQwSn3vuORkBKb5bSYkZYMWK
zjCMVLrmT/BImC8Dxt4gu8Ykr8XuLS/L0L2aGkHAULiL0SsSQiTILbR8d5TYG4GrPU4robcHilqGItAC
BGpBKAjKDuKtAqkhBhwky2RiI7FTUt+/f7+cffbZRuIk4dcjddZHaR1W8BwXuN1HSRy/us8leQblmhED
83ZCskR9UruT2mIJl4MWmz/pcqt3WR5/LN/6sLOwZGLnVMf06dONQeLHPvYxmTdvnvFlHzVqFPzbQxKG
xiQGNTzXYi9b/Xvptv4ROX38DbJj1MWyI7EWex4GTBhumZj8rW5sTt/oeITu4M2EUzoHsJo6DgEl9I7D
VktWBOoh4Hnm4rtGozgswiI13nw5Ve3JUjiJjQFTOKdeVVUl5513nomMRuK3BFhXsJUQ4W/OOXmwvqd6
r8uQ3p1UqbspMk++xn7xuL2I3bYjmdhtHbxm62JwmoKCAjOvzljxDO7zt7/9zQyoOO+enxeQ2jD804s5
WIpI9+W/kG5r58tAEPvOUTNkZ2k/M6hiGF8l9pR3De8j3nn6VKpkngJNRx1iiK9JEVAE0oGAEU7Aufmc
4w0VIXYMpW5PQqcEnpxI6iVQ/27btk0WLlwox48fl0AgYAgvOd+JfX4z+c+Z28TvxMW07bHdzZG0Saip
iecoTfPH1JxyUsto7JjEzoGT1YYwH+sjyRN7EjvxvvLKK+X222+Xm2++2RS1bv165HEEvG4GSrGScYA5
ID3f+olMfOIbWIv9Melf8aEJTqNrsRvITvzhADOOJf3uXK6C4wlUOnRPCb1D4dXCFYETCODzhuTKUZBu
FPPoDoziGPLVSug2J4mMZEOioaR++PBh4RzvwYMHDam3J9HZOluzTW1HqnTdEGk3px6SLAcvltibc09z
8xBT4s2tbX8ysXOOnQZy1113nfz2t7+V73znO8YDYfPmzWgTfNgRTpYDpljpBKOK77X0hzL5iW/J+Suf
OmktdqMxaW7Dci2fMYoz73FQQlO8EVqu9TED+6OEnoEPRZuUqwh4UikJSwIw/oWfOMmEUiPJMDlZ9TCJ
h3PqdL96/vnnZceOHYboSEaWkJLv64x9tiO1/U21oymit9e4JaGT2LnfXn215RNzS+y2rbxG3HmNxN63
b1+5/vrr5Q9/+IN86UtfMjYNDNEbRJtCPgwIMDDjWuz+WJX0NmuxfxdrsT8rvasrvCVbu/Ja7OZV5xAW
RnFFjIqAdKvOoBscOvCPEnoHgqtFKwLJCHjfOFfy8aF3QgVQuZPQPQJpihB5zUqsr7zyitAKnsckn/Yi
uuR2NnffEm1DbbDE2dyymK+he9hHGq/xx9RQXeZCC//YukjqdBvkwMkmXmO99trAgQPlc4g2d+edd8rs
2bPNoGrvXgSnwYpvDE7j+rAWe9lZ4g8fwVrs35Kzn/o3OXvtQuletxZ7F12yFRooJIBUrip3+3J18FYJ
vYMB1uIVAYsA5RXqHvfDKC4M418TyQ3kQcJOJhTmJ6FY0uExiYzH+fn5wqhy/PEcpVh7jfnSmdjuhgg2
ud2p7WnqWmpee8x72E8umWr7a6+1dcuy2QdL3snPgdf4I+FTah82bJjceOONctddd5kV8TZs2GBixYcw
2Ahgcfk4XBFjZViLveoDGfDSjTINa7GfvWGRdMPytfXXYm9rq7PkfuCKFJRqRlLSlA4ElNDTgbLWoQgA
AX7eGEoULCFxrLpm/M2otoV0mCqhWzJJBo7Ew19RUZGR0rmqGFXxlNZT70++r7332Qa2mduWJPapsdTU
NXsP81BS5xQE91tavy2noa0tzxJ7Mp68xh+x5vmxY8fKt771LUPsdHt7//33EOHvOCziQyB2TJ/4CkDs
52At9m0y4IUvy/nP/Egmb1oixYgbYIgdz5wruzWORkMtzMJz5v2g2xpUUkw3Z2EfsqzJSuhZ9sC0ubmB
gBssBJ97c+hxWLsnS4bsoSWRhkiLpEJS37Vrl7GAP3r0qCG6ZBLqKJQsmTdWPtvdnqmh8qi9IKlTYmdq
CKPWtoH1sTxK5ST3ZExZL5ONOjdp0iT513/9V7OyGyPQrUbsAC6Fm58XRPx3kH+gyEjsoSNrzVrs5z/7
Yzlr65uSj+fOld04HMphYseLwB66iJ+EOQmm+fPb9+UwheqfZASU0JPR0H1FoAMR4Ncsjm8cSSOYjzn0
hFFcLBY3Kl1btSWohsjM5iHR0H/6COKR01iOC46Q4Oy9Nl97b9kmqr1bmprqS1PXGquH91Ba5xQE2xMn
sEi2rLbiwHI4yCKpN0TsLJ/ETu3IueeeKzfddJP89ne/kzPOOMP4sNfWhhEnHnYOcQSeCZQgah/WYj+4
XAb9/Qty4fM/l4nbV2AhMreO2P1Gmm2st1l63nskmDsKeyMvmZWlHcmeZiuhZ8+z0pZmOQL8vpEKaR0N
RTn+Qu0KlidxNCahN9VlkjolVRIOfdW3bt1az3jMkltTZbTmGssliaaWn3rcmrKT7zlVeSRV5iEGeVB3
c56bP2t/0B6kzvbw2ViJ3ZbJelkPnwGJnW3gMrg//vGP5Ze//KVZRe/9998391Jid0jsoe7GKj5/3+tm
LfaZWIt9PNZiZwojvn/ukTreeJh5hPIKEoRuuqp/OhABNVboQHC1aEUgFQEjtFBU5wItUL1CpmyQ0Hnf
qQiNeUgoJFeSy+LFi43P9IQJE8x5ElFzymA5rUmskwTHNjSVmmpDY9caO896GrpmDeao8uaPBOtJ7p7h
XkP3NNXm5Gu8l/3kYIGYWo8D2xZet8TOqZDLLrtMJk+eLG+88YY8/PDDsnbtWmNQl4eV3cLhGhB7L3Gw
bGsh1mIftg2BaYbNlu2T58im3kMkiMVfciY+PF92jHvcaESXUE1+oTpwXyX0DgRXi1YEUhGAWRtOwcgq
mAeSCBtyIhmQLKz0x3tIEpZIUstIPeZ9zEsV/DvvvCNvvvmmIZiONpaz7SWx89dQYrsaS01da+yexs6z
LSTwsrIyE/GNpM6laFkHcbBtbez+5py37aVGxC7Lau/jNf5I+JTY2Y6rr75afvWrX5l5dj7fTZs2AacA
1mIHJpDYzVrs3cZI4fZnZMxjn5PR+zZIJKckdbzr5r1IxHO3YOm2wxBo+F9hh1WnBSsCXRsB7x+cI9Vw
cWJgGbBAnTRNZCxppO6fCjUSFn+UENetWye0gGc4U84zn0qCPlXZjV1PbmtL29tYmacqJ7XO1HJIqBzY
9O/f38yvHzhwQGg0aKXq9iJ2lmOJnXXadrN9HNyQwEn6vXv3lk9+8pPy61//2ri8HT1aLtu37zDtCfjw
zKI1iBM/xDz3M976sxRHarAGO6adzcAvtXdZdsxOcN0CX0wl9DQ9OiX0NAGt1SgCRMDKqzHjmssPN3gd
5EBSsGTDLYnhVOTVEKIkb5L6Bx98YObVy8vLjfrZlt3QPe15LrnNyfupdTR1LTWvPW7qHnuNW4tlz549
jZEajQ4ZYa+iosIMcJinrXiwDFsO59dJ3pbY2V5es8RO4j/ttNPkU5/6lPwOhnPc7t692xg0cqAh0SqJ
5/eV0IHl0u/4QRAgjOnM3IzteRZuzYuNdidL6GsX2dc/CzuUHU1WQs+O56StzDEEXLgtiQ+/hCSWqnJn
d0kKrUkkdUqpXNDlhRdeMOSeDgt4tjWZKJP3k/vRVL+aupZcRlP7tgxiSsIcPPgMEPtgQ6A0HCQBt6fL
G+tjX1kuf8kaEV7jj6TO9gwZMkQ+//nPGx92LtlqFt3BVAETDefyjF1FU73LqmsYmcLOIh5PSOgzs6rx
2dhYJfRsfGra5ixHwAWh5ONbB8M4EAETP/apqbF56dR8DR2TVKhup9T40ksvmflbHjM1RrQNldPWc6yL
beHP9qc19VuSbqg9jV1jfayLZFpcXCTjxo2Tfv36GW8AEjuv2YFOa9qU2ha2g3g3RezWh53EXlxcbJbH
5QI9HNi5IL9qqKhzJvHVNn2jBSjSDPNX/3QgAkroHQiuFq0INIZAJRzYXMSNY+J3L1VCtyRForH7JnML
/vBeGoqRyJcsWWL8o0lyluhaUFSbs1IlzWhqrJttaohAW9PP5tzDPCRaYkxCP/vss7GKXZHBY+fOXUaK
J0ZsU0PtaknnbXsaInaWzQEEbRtoAb99+3ZD6kaixzXx5WEVvhz5JOO1xX/eK+5Xo7iWvENtyZsjb09b
INB7FYH0I+AEQCBYQtUkfMtTCZ0ff67PTZUxP/iWKFraUktQXIZ1xYoVxgKeZNMYqba0/ObmZwAY8KqZ
O6YFeqrKu6n+NXWtsfpT7+Exf5TWuR05coRMmzYNFunVwGQZVlI7gDYhJnvCIt7i1lj5pzpv6yfWHMzw
x7I5j884/MSAz8S0B8wnLmwoAogeaGwrMLA4VQXZcZ20Tt9KNYpL0/NSQk8T0FqNIkAEzIcaZO0DoQvX
RMcZ/peqcieh0Jea1tokAhKDJYnWIMlBAY3l6DpFf/WOtoBPbaOtv1evXobUt2zZYqR1Kxmn5rfHTfW5
qWv2/tQtNQRMVIvTzoDS+pQpk43R3NKlbxqLeOvD3lZSt3Wz76yXBookc4s9Sd70gSMdxHb3BQskj4SO
Z08ezInEjjiOEnqaHqYSepqA1moUgWQEKkDmLjSRhuggqXHlLrvWOT/yJBNeI+FZF6z2IHVKhQwT++KL
L8rhw4fTZgHPPrH97M+IESNM3954Y6lZrcyT3r0+J2PU2v3mED0Jlu2hhNynTx8Eg/mIDB8+XJYvXyFv
v/0OSLfGaBFYFp9Da5MdmO3fv1+WLl1qBhLEgGWyfiY8av4VhKyR4wkqzxEJnR3Dey5K6AaJjv+jhN7x
GGsNikAdAkb2gjRWVVAqbvHp0LSGoWUNGgvsefPmmVXUSDaWlPjhp3q8b9++RkVLSd5eqyu0BTssjwRK
1S9JnQu8WMOwFhTTqqyWHNmHoUOHyqhRI800wNtvv23IzbbDSsZN9bOpa401LvUeHvNHUicuJPSrr75K
Sku7GT9+G7qVEjuTbVdj5aeeZ5m8lwO1xx9/3PTRTqGwrHrPkip3P2zHzMJkuUTnQCXm0p1DUxoQUEJP
A8hahSJgEWBYz1AsKnuKusuxsdeK/8gzEoMxFD/8/Mg/9NBDJtob81v1MM+TeChJduvW7ST1vC27uVsS
jVV1v/LKK0Y7wGOmlpJWc+u0+SyJUt3MaGqMf15TUysLFjwlO3fuNO061fw+y2gsNXWtsXssziR24kA1
/JVXXolBT6U899zzsnnzZoN/SzAijhw4cWph/vz5dfcTe7aR1+s0LuwPVtzzhQqkENMrENaRp7HWZuF5
ldDT9tCU0NMGtVakCHgIQAUJqSUqy8deIRVTfiPBI0slBvW7Hx9zqsQfffRRee211wxxp5Ib56BJhFZd
21pMSSgkMg4kGCr23XffNUTDcx1N6mwzSc3aDUybdq5wKdKXX37FSMY2FjvztaQtTZF5U9dYDxP7TsJl
u3r06C4f/egVMnPmDNgdbMaKdp4/P/M0ZTjH9vJHXBmx77HHHjODBDuA8mry/iZL6JiQgIV7SI4Yt7Wc
MYrzOuqqhJ783DtyXwm9I9HVshWBBhCAjCZBqFgr/UFZfP7n5eg5t0ig/C2svUYfZEe6dy+Tv//97yYo
jF2i0xIbt4yAxh/Jpy3Jkg8HEatXrzZzvBwoWMJqS9nNudeSLKV1Bn/52MeuNkZp8+c/YhY0YfssEdr+
23uaU77N09Q9qdd4zB/JllhwOdRZsz5pfNhpDb8IIXUPHTpkMLKDLds2u+XUwSqsjf7EE08YwzsOApiS
62JeK6FjFwk2E4gQh+jzxpkxZ5Tu6IhPjeL4gNOSlNDTArNWogjURwA26xJCVDA4UckrU+bI4Ytuk8Cx
97mgqsTijvTq1dNI6U8++aRZZCSZZEnklNIZJ5zEYImkfg3NP2J5tIBnsBWq4Ckhk0jbOmBobgtIdCR1
tuHyyy+X8ePHYX7/JaPupgEf22LJs7Eyk8mysTwtOU8StsTOus86a5LMmTMbg63uCKn7IgY/b5rnEgwG
TNuIFfOzrVwg55lnnjFuhzzHa7Y8+6y4rSehG7e1fBNcxvEYviXNzey8KqGn7fkooacNaq1IEUgggA82
te5REgDdlUDsr024SvZ95HcSqNqB+VQQfcyBFN7DSHo0lqNUaKVVlkLpjn7qnFcnaViiSNTQ4g1Jh5L6
wYMHjbEc67Pz+i0urBU3kPBIcOwH1e+cw/7www/lyScXGD/xqqoq0x4W3ZK+EpvGUlPX7D1sF+sj3rRf
uPTSS+XjH7/WRHh79tnnZOXKVWafUjnzcvqC4XaZl/fZtvKaTfZ51RE6mujimTuhQglxAGAyNt5uW07m
bx1P9+DASERTWhA48ZalpTqtRBFQBCwC/GTz482YccFIrbw54iLZ9dHfiS8K56VYlUTiPqN+p5X0X/7y
F2ORbkmdpECSoVTL6GeUIq2UaMtv6Zb305CLftIMF0sjtVTL85aW2ZL8luhonHb66acZUh84cCDcyN7G
FMSzsn79elOcxcCSZXOIuaXtSM1v8SZGXGjlE5+4Tji/vnXrdtM2Gs7Rx5xkXloKD4YkMmdZvD+5nSzH
qtw5zcKV97ikLmOf51xSCT1tjzQH3560YacVKQItRwAfei9hm9ilmp27oUi1LB80WbZe+WusOpkvvvAR
kLpfShDzm0uA3n///XUx2S2ZkRRIwiR1Et0Jkmh503gHiYbqfZLPq6++akiU5fLY1tm6kpt3lyU+knpJ
SbFceOEFcu6556D/xzAdsNio4unTzTa1RQ2fTK7Na5lnNMf7iBHrHj9+vFx//RwZO3YsyPxtuKftlDFj
xhisKH0zWdySJXSeZxl1EjoePt+AWgztanCN8QMTrwazZn9SK/e0PUMl9LRBrRUpAo0jwA94DNJZPkj9
vb6jZMM//JfEiweJr3qPRNyA5Cfc2u677z6jhrekyxJJ4iS49gpAQ+ImAVHlTqmTIWNJTKci0MZ71/Ir
rM8S3sSJE2XGjIugxi6R7du3C1Xdy5a9ZYK/sI1MLRlssOzGUlPX7D3Mw/pIylxghW2bNesTMmjQQODm
NxJ87959kP2EJX8yodv7vcGXyQaVe0QCWLAnH7hHUXbjLbStyIatHZaolXu6npYSerqQ1noUgToE6j50
dWe8HawMBlIvCFfLhh4D5b3Lb5Fon3PEX7nNuDQFAn6jYqf6nVHHSAyWKKzU2F4BaEhY/FGlv2bNGnn9
9ddNABYOJFhXOpIlPkrrJMtLLrkYqvjTDdG/9957xvBs48ZNBgdrNGiJnfe2Z2qoPJ4jFqyTg6mrrrpS
LrjgAgyuQsa6fdCgQXB/61E32LD9Ybt4Hwndk83x10VwG38enr9n5d6ebe/EsjzVE6wDTBuw1HsntqVL
VK2E3iUes3Yy4xBI/rSBEOoSdsOQ0vIjNbKjuKcsv/T7UjP4KvEfW2N81ZmPLmuPPPKImecmKVByZiKx
kDTaKwANyyTx0FiO8+l02eL63emeV2efSOo0NLvooguh1h5tBjI0lKNVPi3iacRnDdMsqbP9qYllNZYa
u9bYeZbDARWvs05K5+PGjTVGc6NHjzaEXVpaJoMHDzEEb58P77OEbso2jz8qtQgHTO8HPs2kN4LZsz15
hD4r17qVeY9FCT3znom2KFcRSCbuU/QxTPV7tFb25xXJmxd9TSrH/rMEjq6Er3IIbm1xEwr2+eefl6ef
fhqR1mrMvDdJwiYGoKGLVfI5e62lW5bBhUxodf7yyy8bS3hL6i0tq7X5SXxWBX/WWWfJeedNM31mOz74
4APg8IyJwc5FV2zbmiL21HYYYk092YJjez/rpBqec/9XX311XbyAvLx8WMNXm+fBvMTUGwR4n2AOM+Jm
pTUrs7eg8kzNyk55IxOP0G/N1IbmTruU0HPnWWpPsgqBVBkMx+aUd54OPyT1vFhEjiIAzaJpn5WjU/4d
pL7KLLsajYHU4bJG1TtDix47dswQmSVwkgXVve0RgIawslzOV5MwSeqcy24NcbblEZEI2S9K64MHDzYq
ePrjs220IVi+fLkhdvrTU2vRHmp4S9QNtbuha7aNbGf//v1MsBySOwcjbDfD3NLnnpoV+vuz7d49ePzB
HAt5TlMA7532DB1uVgm9ofeoPc8pobcnmlqWItCOCFDA4ZxqCB//KD6Mr5z1CTk0/ScSOL4OVxwJg9Qp
idOd64EHHpADBw4Y0rWkzi1dqNozAA2Jkr8lS5aY0KYkTaqdSWDpSCQ//jiwYN/oOjZq1Ejjasf5fqrh
X3hhoQkj++GHRwzRn6p9LK+lqal7bBuJCfdpBX/FFZfXYVRTE8ZgI4i2zzTYkex9iBIXQix3pvQg2dIe
tzI/MAAKnoTueH7prSxJb2sGAkrozQBJsygC7YdAyue6ISJMykKqYQCaEALQ+CGtLxlzheydeRus33fD
kArLf8KuqqysVPbvPyD33HOPWdmLkjTJhD9KggxAQ2M5koslmdb2x95PVzlKxLSA5zmSvL3W2rJbch/7
4hGhD1HcqII/z/SVgxj2l1L6ggULEKN+pclHCZ7t4y85sZzGUlPXGrsn+bzFm22i7zqnCejj7/d78+5n
nDEYgWo+YrCLYdW9MEidqfEWJZeeJfvAGyQTkltcyzU51b1MewoW5Exrl7ZHEchdBOpzSlI/ky9w3zum
3jIG4uGXMIh59WXDp8uuj/wKAWgqvAA0iCpXVFQAVW5Y/vjHPxrJmepwm0jqNGyzAWh43BayssTIMqkd
eOONN4zEnE4LePaNfSBZktgZC/7SSy8xIXG5NGxRUaGRfhm5jfPrNOpj+1LV8Bajlmxbgh3zWk8EGsoN
GDDAPCeep+qd2pMLpp8v4ZrDEk0QekvaktF5qXLnO+y6eXK1sfVDc5Pf8YxufVY2Tgk9Kx+bNrrLIJD0
/eOuCyLIg1vbitPPlC2X/wJh5grEFzkKlXxA8kLwV4fk/Kc//clIz5RKLfmQxCm5072KZN9WUif+JFOS
Oo3SFi1adNI8fjqeke2fVcHTJ3zUqFFm6VPWT8v48vJy47vONjJAD0md96VK68ntteUmn2vLPrFimWxb
JBI2+yR6tvu0Af1l7ORrpAqy7InQr22pLUPu5QiUWhEfLDm37vbUD0nvc4a0MqeaoYSeU49TO5OzCCRU
xfweUgXPADTv9xkuGy77MQLQIKBJ9T6JQrOJla2MMRzn1BnpjSRiJUQSGMmMkjqJn5JtW4mLRMWySJR0
IWMUN6vyT9ezsH1kf6j6nzzZU8Gzv/QAYHs48NiwYSNWQHtS6MPOdjcmrTeFSVPXmuqvva9v3z717Bx4
TzzuyvBR48SP0K9hPOCc+ijzvaWELnmeb2VTIOm1NiOQU+9Om9HQAhSBzkKghZILA9Dkh2tkY9lpsvrS
/0AAminir9ouMQhDLsiKpM111enaRmncznGT5LjP63Svai9Sp9RPK25Kwdu2bTPGaISyKSm4vaEmaZKo
2achQwbLxRfPNCr4ysoqUxVJne1ZsuR1BKX5OzQLewwWydi0d5tSy6P7Gl0ArcTONsfiMSku6SYjyrqR
3aUQmuoWvg6p1WTKMTpiXCkx/4OoSJo6HAEl9A6HWCtQBJIRaMQmqJHToMTkm+vtG1KP1sjOwh6yfMa3
peaMK8V/fIOJOEZSoyHWiy++KI8//ng9X3VLsgxAQ0tx5m1rIkGRGCn10pVu7dq15vhUFuZtrTf1fhIk
f1Rl06WNKvgRI4Yb63fbRg5kDh8+bCLNvfbaEgTLqTBt5X1NpVNdb+reE9f4PFOeKQ6J08A8WDhiwOFD
M5puyYnSMn6PEjoc8mD9AVLX1NEIKKF3NMJaviJQD4GUj3m9ay09cI2vuglAg6U3l57/Jakc/VmzrrqL
FSspMVMS5/rcf/3rX41anOpnEhsTiZ1+6gxAQym+rckOFKiCX7lypamX56wE3NbyW3I/CZIDFdY9Zcpk
mTbtXNNvEj0T7QvYToa15Zrz69bRFdAjVrbZ9sWcxJ/2IXMxVu4MMJOKCQm8NHbMVMc3JGcI3fTIgXTu
9wj91hzrmulf5vxRQs+cZ6Et6coINJfnjcRzAih++G0AmmOwkn556qfk6KRvw1d9DYyRghKORGFJ3cuo
we+9917Zt29fvTlcEhcD0NCf3RL9idJbt8cyqd7etGmT8VenNTcl9/Yqv7mtIgmzThL70KFDZebMmcZI
jq5jvMZ20ned1xctWmyWQaUNAAcD/LVne+0AYTsC8oTDkQYHCH4EfqXw3txXobk4dGo+7331SyTsBZfp
1MbkfuVK6Ln/jLWHGYUAKLgh8auhcw22++SMPEP1ewhzsXF8QF8581o5dO4PJVCxEcQBS+oIA8x41t53
3XWXIXdKpyQZ/khcVL1TBW/PNVh1C06yTJI6BxCLFy822gHOs1tia0FRbcpK4uaPknmPHt2NCn7YsKEm
DKvtO69TDc+2LljwlNDVjQFqKEW3RyIWHCBQzb969XvAxZtDTy074kAzjcTnmROkbl5V0xO/5BV4EvrN
pov6p4MQUELvIGC1WEWgQxA4mc9NNTzNhT2CIGh/FAFoRl8qey/8qfhq9tQFoCkoAIkj35133invv/++
cV/jzSQ2qtxJau0VgIblksg4cOCCLjSWI2F2BqmzLSRtTkFQUzBlyhSZOnVKQkr2AGVb2TZOSaxcucpY
w1PDYAcErRno2HtI5vQCWLjwRYMJy0xNfC7lvhLD5vwoGxpMzZSNx3i3kPzBaMST0Oc3OJzNxp5lZJuV
0DPysWijchKBk7/j6GaDJxvv/im+9HGQBQKxSjCCADRDpsmumT8TXxwq5liNRON+CcLYmJHU7r77bnnr
rbfMXLIlGJI6pWr6qlM65bG91niDmr5iiZJlvfbaa7Jly5ZOsYBnK9kXtofEPnr0KEPqNTUn5rMtAVMN
z2kCruL23HPPGcma99r7m+6xN0BiWfYe+uk/9dTTJna7jViXXAZaZVwOt/u682bs50hiYBka7PuMmZ8a
xaXhsSqhpwFkrUIR8BBogLwbOFUfrdQMp2B03ExSNwFosATrigETZMvFP4bXUD4C0JRDimd8D9eo1+mr
Tt9xEg+lSCYSLyXV9g5AwwECpeNly5YZ7QDr44/El87E+ti/I0eOmPn9PXs+MESbrF4n6fOYGotdu3bD
S+AJs5IbSd7ixDx2AJC8ZV8skdP47c03lxkXOQ4iSOa8LzmR8/xYC/2Yv4887euGpxMTxP/DfzmS+Hix
rCzeR4/Q1y7Kma5l4hNSQs/Ep6Jt6gIINPRda+hcChQg3+Ykfkej9FVnAJrew2T9xT/0AtDUHADhw9Id
xH366adDtfyEcd8ikZNwLTlxnxby9Jmm0RhJqi2J5TKxPAZ2oeW9JU57rS3lN+de1kcyZ+Q4rlC3efNm
Q9AffLDbLA1ridhiwPycMuA9bC+D0tDHnonEbvMnb3mNK9/Ryp/ugtyyDA4QGuonCd3nxGV9cATuDEgZ
Blv1KZ8lZnGCmQYJHSoiT+U+Y2YWdybzm+6F48v8dmoLFYEcQoDk6BFc2zp16nKMrzpIfVO3/lJ70fdk
/Jt3SfDAMokVDYLqucb4qi/C/Dbnua+99lpj9U0DMpIUSYhz6gcPHkQo1Yo6wm9Lm0lqVOuTGGl4dvbZ
Z5tjDho6MpGcOT/OvjzyyCOG1BkWlgMZkvOhQwfhq18Nj4A+RpLmeWLA+5gorXO50+eee0GGDRtqQrjS
kDCAKQzmZUQ6rhfPYDW7d+827mkcvFB9b8tI7R+XLQm61XI4OEj+4PTHKxGRCjzStg2dUmvp5GOjcqdx
YUJC7+Tm5Hr1Sui5/oS1f5mJwElczC85SJ48b64lMth8lJBPpZ5uJA9JPQ+Luuws7C41F3xdznq7m+Tv
fFpixSPgTVRjJPHVq1cbUp8zZ45xY6N62UqUtH4nudOwi9u2JhIcyY7kyvC006ZNM77wdiDR1vJT72d9
lJI5lz1v3jxDthxUJGseqJGorKwwC6cwPGthYX0iZhnMQ7X5jh07zGpuHCB4hB43rmixmOf3zvMcAPAe
/hpKZnrZjUrcVyDP+8/Es3WkOyT1cmw545xDieMWBIyDWohp4/Lc6l2GPShVuWfYA9Hm5DgCJN26lNiv
d67uInaS8yafb/m+IXUs0XkgWCBvnPsFqRxxA3zV14vrR/xwzO8ywMyuXbuMsdyePXsMAZKMrPqZ1+mv
3hhBtbRFLIfERymdbm2sk6ptW19Ly2ssP+shmZOEH3zwQWPs1tA0Auv1+zGDDVIm8VPatqp0O7Dh1pZH
yZuSfQxr0jNffr5H4iybqWmc+FxhuOiLyRvBc+UZKZHeMIUrx2COBo2nHLiZGrLoD7vri+dnUYuztqlK
6Fn76LThuYlA+5F4Mj4slQFoQvGoHEcAmpcmz5HyCV+Fr/oGfGwDJgBNt24lRq18xx13mPllEiGTJVlG
lGvPADQkPTtv//rrr5s6KQGTIC2Jmga04k8y+XKunGTO+jhosOr01GJ5D+u2Kvh9+/YaKT51/pvlWMJm
fiZbnz2fWvaJY+qgsVSJ1MrKwNlypwyQHlC1Y/iQIHPmzEFSdx3vZRo5hd3X1EEIKKF3ELBarCLQNAIg
gqa4u961ege4j8f42dMJUjlRX+L6iRNmj2cpqQcRgIa1zbJtAAAtb0lEQVQEtGjc1XJo6vclULkVRfok
EnWNpElSJamvWrXKEKAlWJIV553bMwAN20ECJdEuX77cGMxZUuW11ibeywEJQ7o+9NBDderyUxOuVyMH
GrQroBU8tzxmalObzP1YxlZgqBicKr+UIVLshqXSK5h/kUjmdtv6/puiMugPcFMJPQ3PQwk9DSBrFYpA
PQROImB7NYmkzakEMXPD1Oh93uXG/54ol0Vx+dUAiRTS+pIRF8ve834kvtr9JgBNNE5jOB8WNuku99xz
j1lohRIqSZdkRumW88O0gLfnrJTaeP1NX2G5/FFdzUVd3n77bVNPqmTcdCneVVsW1fkckHDOnMTOtjaX
zFkS83KQQYv4F154wcyZswzb5+a0JTkP20Xsg6F8eTc4TX4WHypFkMxpChg5icCTiBz35UTyJST0nOhM
5nZCCT1zn422rEsgkGDremSdOFev/w2dY4aU87Yce9oeJ5XFS/RV5zYAY7llZ5wju6aD1E0AmmqJuTR8
85Zgpar6pZdeMoRrDeJIdiRfkjol18ZU2ElVNmuX5dJYbefOncZHnPPr1BaQDJuTDGmiXyRiupk99thj
ZvBhNQzNKcPmIXHTMHDnzl3m1BtvvGHKtNHmWtIm5g0E4IYdq5XlH8Tll9EBYHYTuR2hejEH74nkXtW2
r2bbvH7bNmf0FgqTjG5fjjROCT1HHqR2I8sQMEQLSrXEW9f8hs7VXTyxk3r/SeWcyHpir34m0gUD0ISw
BOuKAeNly0U/BMMXIgDNMRB+0Mwf01f96aefRqSzp0w8dBI4iZckTuIkqVMabk9S52CBRmm0gGf88+aQ
uiVzto/ku2DBAhOfnn1vLvlanGxZ+/cfMBbxLJNaiY0bN8oiuPixbclz/czf2I+DIOY9ehSBbJa+I+te
uFuuffmncu6ud2HTgBjzMEr0434/ME3o2m0z2HDvnNmeOJ2Ne9DvKKGn4cEpoacBZK1CEWgagQTR1ufb
BNnzJH72miHyhkqzGey1xH32EAWk5qAKn4pgBqDJYwCankNl/YX/JvGi0xAD/iBWawvBrS0sAwYMMBLz
ww8/bPzRSeQkMBI7ya49A9CwuSyXgwT6djNcLK3OLamz3tTEc5SoSZ4k3Geffda4wbGchvKn3p96bKVz
O5hgOfzRsp2ue9RYkNxt9DdiwLp5n20H28vz1DJwidaFCxfK3r17pKist/g+XCcDX/yOfHTJHTL+8DaQ
egg/uMShDiOtJ/fRdBd/ks+lNjgbjq1RXDa0NYvbeNK/8SzuS/Y0/RU3IBc7Uf/Dxx+XouJrpbIqgn+x
3lJL2dMLbWlbEaj7SCd9sM05HrPwpK3ZNydPfNxPypu4bm7lPu9PvseTJHk59TyzBt2Y1IJcBlV9KOPf
vkeCB9+RWOHp4kCCD4LEKZkOHDhQ6Kveu3dvo5JONmA7dOiQMSCzqnlTTxv+sGwSKYnzzDPPlOHDhxtN
AM/ZeXtL5tySaJcsWWLc66gxaG0iKR84cMCo2+1AwpZl1fckarryDR482Fj+c6qA/WY72F4G4uFSrJw+
oFGdvW4GB3TMxiDKX7PfbI+O+4ysH/UR2V3UAwvrhBEvDvHccb3OZgI4eCM6bLPvix2V4qKAU1H5P9E5
xd+WxLfP4qnb9kVAA8u0L55amiLQfAT4obaEa+8y53BwUpAZmyFB0Dw8KW8D5dnb6rZkhKQy6s57FvB5
IJSdBd2letr/k8kr/ir5u55HVLmhULfXGKmXK6ZxYZdPf/rThtwZDMYSLEmepEZDsvYgdUvWlNbfffdd
I+2OGzfOSMGsk4n1kLwpldOYjiTb2qhzJGuWRcnaEG+ijiSIDGHzmCp4kjYt89kGEjbvY5s5907tAhMN
8rgYDhPLtwME+rtH8/oYibxs1f/K1B2vyumTPiNvDZostXAjzI/RYA6KavOM8bzqiLxux5SZLX+gCVKV
exoelqrc0wCyVqEINI0AP9INfahTztlDfuRPSo2dSz4Ptbs9rNtyB7/EcRjSaR4C0BxEAJrXp/6TVA6f
Bbe2TWDOPLi1RY3amYTFddU3bNhg5tHZFBIZfww+054BaGy5JEzWxxXiSNgkUf44oHjyyScNsbYHmVM6
HzRokCFeGzTmJKhxgoRPAiexk7TZpurqakPkJG6q5/ljG5msOp5b3ldQUCgFIajpYXwYKRwmvupDcvrL
35ErXr9Thh/bLzXBfBPTPQCjOTP8sn9SB4Cm9Cz4o25raXlISuhpgVkrUQQaQcAyrCVYZjPnTpCsR7bM
YH9JZTWY15aRuIXZbT3cb6icxHnWEHb8JgBNBRbVeOnMT0r52H8GqW82AWiiiIyWlxcyRE5JnZIzpU6r
iiYBt3cAGjaNBEpSZ0Q5GstROubA4tFHHzWrt7HO9pDMqdYnSVPCpvteU4l9Zbu4JVHbQYZtL7dcOTSZ
zG0+bjkQoF9/QQhTC7RXKBkthduekYnPfl+mb3qVinlI60HJO8kSniVnUeJgxIH7PRNMM8xW/3QIAqpy
7xBYtVBFoKUIkEqZUr93PJ90zh6SoE+S1hoqI/UcpXRK0yi2Xlk8xkn8z6IjoJMgiCSCTIvGXinT84ql
97u/xZz6IIliepqERBK9//77Dbmef/75htisqppERYLjXDQTCb+tiWXTAp4qfRI5y2RIVy6Swnnr1tTB
ezgQILkOGTLEbFkPDf+4bW4iqScnS+Is3+5zm3xs97t1K5UCtJ9z7eG8vuKHsr3/4u/L5R/cIOsnz5Wt
pX3N+vY+VBEFy3tIth3P5PZ26D6hcRKx3Du0Ii286SGo4qMIKAIdj4AlO/ONTnyozTns2+923TWesycT
TTspb+K6zWez22NzG0/aC8ld9M7xbwyGWfACNwFoXh8+Q/ae+wMEoDloAtDEOb8LwqeFO8mVwVc4/0wS
JxFynypnXieRkfBIYG1NLJfkSwM9Wr/bFdNaUzbvIZlT8h82bJgpl8fsA+e9WVdrkkfUHDjVJ3PiYKV4
u88tfxyoMAJfWUkhfNMdiRSPlcLtz8iZz/1AztmxXCKBoHA6JARszdAhZQDRmnam+R5PQl+bPDpNcwu6
QHVK6F3gIWsXswABQ3YgvAY5r6GTzNvI+ZO6y3zJeZPn0hPnU+tPlB3DljkCMJZbNuhs2Xnef4gTr8Hy
1jXwVQ+AECPSv39/Q+j0/aaq+oThV8wQFa9z3pgE2RriTe0OBwysw/q/p15vzjHbQame6nWSOSVyS+Ak
WBvetqXttSTOULqWrBvaWmK3W+YhRrQ/GNAfvv3+uNSG+sHDoEoGLfyWXPbOw9IDQYBqEKAmD6F7sybx
5eEIJJ5YnOVmHmHEoqlDEFBC7xBYtVBFoC0INEayLJPX8LOfxATxeuTe2PnEbeY+e6Mti9vUVD8PfdVt
AJp3+4+VLdN/AIYvEF/4WJ2vOiVxGqzRV52+2iRIJpIkyZfXLQG3lCRTW8djSvypau6G8jV0zpJ5WVmZ
DB061EjNlsxJqhyUWFezlqjdWZcl9IZIvKFzltDtlnk4yBg46Azp1b1EInHE2C8eLmWrfifTX/6VjDi6
T6phsEhjOScrpHS8SyR0n+O9EMmvVkMPR8+1CQEl9DbBpzcrAu2IgCFnfPFO+ujx3EknUXHKOXu/PW8v
2/Mpx3VF2p16+ZC57jy/yTYATY2s6TlY1k//rheApvaQWYKVAWi4EtumTZvkgQceMD7YltRJiiRKkjrV
21RrtweptwZ5S+bWh5wEakmbpEoypzU9g8G0dMBgCZt12J89l7y15J28JT485pZ5g8GACegz+IyBiCQX
lZrCkZKHuAATnv03mYooc7WBvPpW8K0BIx33uAlp3LVz6DTgSEfFXbMOJfSu+dy11xmNAJk3wb6WVE17
SbLcSVxPZKkjXpMncdnmsefMNnFf3TmPeOoucaceqZ98HIHlex5Uv5u69ZNV531DIj0miL/6A29ddZA6
DdQOHjwo9913n2zbtq1OUidpkqioyub8NEk93cmSOdtA1zSmZDJnsJj169ebFd8ooXMYY67D6l/4ayJZ
ArdbS+A8tvvckrRTjy2xJ5O6JXYOPEaNGiWlRSGpdrqhSREZ/MI3ZMaaZzHlgXjzaBeNFzOaI6lNEdeT
0JvAUC+1HQEl9LZjqCUoAu2HgCVwS9Ys+SSSNSd5IXHN5rFbnmcepLryEifMhtdtBpOJGbmTkpLPcd87
9kg9LLsKy+Sdc78sNQMuFn/VduOrHsW8NKVwupTde++9ZvU069ZmyZMBaKjutmrulEo75NCSOefzGZ8+
WWVPQq2srDRLrVIypz85CdXFICTmwjI9fEScyFEzvcAIb40lS+bJW5J3KqlbQrdEnrxlvck/3kvjwpEj
R8rAAX2lFuOgKAL99HnjZrli2f1ShpgBtf6ghDKa1M1wg1F3kl+oxmDU821AoPG3sw2F6q2KgCLQBgTq
CDz1+3eCVOvzb0o+e3/9TAkSR16bPZHPbNhcu2PvN/mYP3GDPUbWMCV1RDNjAJolUz4tlUOvg6/6FiOp
RxPz5iTyP//5zyboiyUxS6Q0/qL0aUm+DWg161YawJHISeis06rTSabHjh0zvuxcupUDEZ4z7UQwHR/6
VNH/Iqnpe64Ej6+FUUAYxI4ozSnEbonbkndjW4uDJXEe09/dHtutJXViyDzcDhkyRMaMGiEuDBRrYQXf
be3dMn3Rb+W06qMwlsszpN4sMNKdCXwOd3y6SCdepHQ3oOvUp37oXedZa0+zCgF++yjZJLYkVRpBmcPk
a8yC8yZrIo/tp81rtsxgE07Yc6ZcHOLYkFxdPTyB/PXKtse0fHcNqYewpnolyP3FiZ+QmXklUrb2HokW
DgFpwoUNRFRS0k0eeughIwHTV52EZSVzSuk8Zgx4JpJgRyTWRxU7NQO2btbDuunTTql88+bNhuh5zpA5
Ar0EKjbL8RFzZfHE66QAEvBZPUdKj20vSuD4RokHy/Ar8QzTEAOf97D9tg92324tkfPY7p/YelHv7DHb
YPPZ+9le1sEBCTUg6zD4qM4fLgV7XpEpLx2V/Bn/IltK+0l+pEYiKYMN3tu5yRgwBmWRiZXTfOf+zm10
VtauEnpWPjZtdM4jYLgNf+yWHTaEZ8/x2Jz0diwZ1tvavNyazCe25ubEORaDY5JHYtfb2oO687yOn8lG
Uvfivwc50ADBLxr9UTk46ZsSqN5p6oGTGs7HjSROlzb6qjNUK6VPSskkV86nc06bdVtSxE1tTrY81jN4
8GBD5snz9iRNrqa2evVqY8jHfCRUdoUSOLUN5WO/IC+BzDnbfxwk+erQC+StC74re6Z+VyKlIyRQtTuh
ig9CNU+f9ojpA8uxWHKb/LOkbbdsB3885pbY2K2V0u2WUjoTA/pMOussKYXPemX+YLRjj4x95TYZeniX
CRnLOfWMSgTVQYD6g2uVbzr4wSjAHQywFq8ItBoBkMEJArWl2HPcIplN6jl7zZ73soJZvJ16W5yzx6aw
xD2mbLuflKdemzyyoq86VX0+SOWvD7tI9p79fQSgOQR/9Sjo3JPIKR0vWrTIrFPOsK2WnEjqyQFoeGzJ
MNHqFm94PwmaiW5pVO8nW9aTPBnBbtWqVUYyZz6GaDVkDuIOVG6VwxNuNBHyeJIESZO4EIwB94QK5Q34
47923lfhk/+fEu51Fgh1l1lDHsu6SG04ImGo7ZlIzMlknrpvSd2SOfPbXzKJEyv7o+eAD20sLi6RSWdO
lL49SqXCj1Xa4rUyZsnvZdihHYbU6daWGYnvEJKLFSaLxyYOvFP6t/0RUJV7+2PaghJ9MfFiRFAI0Je9
Bch1mawkUKP6Ro+NpMOeN3CO9kb2DTL5mIeSkT3J+71bWYLZ93a8DPybyG5sl8wxTyTnTc6E80Ydj3P4
P27uBflhjnnZoKkyOfRvMnDZbeLGEDkuUOIDoTqcM1+xYoVRv//jP/6jkdw5t00SZ/Q3qpO55CjPkdgo
sbc0kTRZHu8fMmRInUU9zzNxu3fvXmPJvnv3biMZ8xL6DL1wNE5yPjD5e/LG0PMRPCdqBiocsDBFsQ1w
KgG/cgicb/WfIIV9Rsm4gzOk36bnJW/fIomHYLgWL+YAwldYVORQPZ5cN/cb+jVG7jxv8xs8AEnM75o+
hkJ5MmHMMPFv3Sc7yiNShFHHqDf/5Mp5X5QtPc+Q/HCNG/H5OpfZ8TgkFuV4KIui4ZjHnZV/vDc1K5ue
xY2uWw+94v9v71pj7Kqu8zn3MW/Gw8tjcDz22B6X2oYWO6GggkTSFAQBZJCctP1F+yORqrRSfpBWraJa
VaSoan9UVYUUB7WVUCs1qJaIUoyJZZmGAG2McQTBj9hmMLGxGXPnwcx9n3P6ffvcdWfN9rl37h1swx3v
LQ5r7bUfZ591xvfba+2193nJW9n/+940/pVm+KuCZ+IbEcpHJM8kb8rOs8yWST6pHWVLSfr+MkbpR8qY
570lL+OQvJSTMtn9aJm0adSHtJV6bPtJ60ofuk/KJOn+yet6uoz17bzI9Lh1HzbP+kxSX/pbQJExoEca
VzdMXSZyu57k0UZAUyw61dZ0Wc9LXbutymMQPOwkjb7KCCjbmhv3NrzxL14082u6sbHQHKZpeTII7dZb
b/V27NjhrV692gA4R0/wIhgT1HVwGst0ovU9Pj5u3PcCliwnz/a0ZkdHR81aM/NSRsqPu7z11luGEvSp
XiAe4DzyMwDID377T7zX12wz3yVnfyEu8xJIWLuWp2sTUw58PAVYhYC0Qaxdb71w1Bv+1UteduqEVw6M
XgJMVNLcysdDddgf7ynWN3nJJ1EpF1DnCELMnAI8P3VQrTIKP84fO5PzTk/jAzbZFCYeGe/o9j/0xleu
9box5Kp5kWyNxOdgXqgtY75Rkn7Ylkn3IzKRmwq1Ojz0dXru42BuYqX3x6NFzp6gDOlNajp6GTSgX8Nl
6M510ZIGfhilva/6Qeo/Z7+NF/Al/IHPIFwEpkxLrV2la1UDxnQm/NS2/5DyZzEK5/8dCx9ShsJ63Vod
lstPqdQ1dSDkIeIm1e5h5OR5j8g3f56UGZCPZTEcyjji9liJ5tfa/EK2z98ycTLYcGT39lSm6zqAKz1R
GQIVt4bxRLQnnnjCHL1KlzgtUIIXwYp72bmVjOBnW+pJgE6wZB/6IysC5uyTfbz//vtmzZzudtUvtnOn
U35l1ruw8fHXXx+9r5KtFvAEmByk0ti0hic04FNTTaoGRD7MZKQUyvAZF+wRx/o2Pnm6pjAZ3P72np7e
3Fu/m8r2psqlYoB7+QgATMkHazgeDerkBdBtOfOsn8JY+CIMoGOSwp0E+LxrBBqR4j//+Pu58umPCoVe
+F0rmb7Mye1/dOzkDZ/7VXel2F/105xQzf+dcPBXI/n0EETdeAEXgumBP/W+4TPQwAH6FdL91X/BV+hB
Oq5b90fdca+sAwZM/OG/6UZUyqS8UV7kpJq32zUtG4YRewHYsu137t+8+uaBv89ks6vgTofn2jegzgA5
AvHjjz/ubd682QC5gDopg9ZozRPsdLIBXcCc7u3R0dFLzmUnsJ85c8aAOfskSNYmCfCmxyfGzMzmv3vw
wP4fX48JB46Uweq/mV6bqQzuTcr5jOSFFxpdh3Ie+3KWdVZ8OfjiNu/OoaHBv8hmu77AYDlMNqoIAMww
AJCTDo45CbxFJhTehkgsdeoA3QDACeJBSB5XgAsqgQATphMnjr9/5r0zub6edCac+vmZwYMffvPfPG+K
bV1a/hrgP0iXPi0N7IIBsBk/mDvxI/Dcc+5dfFrvoRPuu3Mn/kbwt7J/d8q79XrfG0fE8Nyg7/WcS3nF
Ad8r5X0vPwV/axmmai++Pj0H/3XF98pF0B74jquQl2j++l5XGRTO2DCAGYoPctJyC0FZZvhMLOOkE/Yp
5HE+Q0oZ1oco40c2mDcyUpZzAiB8xr+xcCYNEJ3dsmXLKoDtPwCgxgBAxlKn5UmwpXv90Ucf9bZt22aA
joBNwOPFr6pxa5kGdQ3olHNiQOt33bp1ph7Lmdg/b8UT6+hmZz8azFGeBrAHkP81vrF+cLDbG5q5cStu
TquSPnM+DS1yXHi6mKJsAc8yXpT7Ud/0B1H/xHvRhOfNoL3/la88+gf4fvxTuO8KHCsb4Pl9HIGbYqQ6
x84xCnhrSiCP8wyI42EzaejVjzAhIogLoBPUgeNBUDEIH4bVoFI9cfz4qfMXJnLdff0DQTUYn7tp3Z/v
3/1309u//v3sG9//enBVf2vM3y1+297B3++u2MnDd+PSldEA/khcchpwGugcDQAsd341BZ+0703cjLM/
Z32vCCAPAeQE8ICgDaAmQBOcB/piSrAOgxiQI6EGjGNZDM4apGvWeK0O0CQGakPjssh4pPkbgk+XoZ54
BgzA170E/o0rurIA9QLWzfvvvPPO72E9+fO01FEfW9Xhw4Y1zsj3Bx54wLvnnnvMGjiBmGDHi0BMYCdP
kOckgGvoDJ5jPe5nX7t2rSkXMBegP3XqVP0oVwJkzTKvoq8M6uYnPvroL19/9dVDANihyQJC1OH5J3Bi
bHXru5anDFF/pny+zDcgFZdV0K6rCx+Rr0Qrh7I+xh1gspG7++67RwHi30EQ24O1MVdhqWcYR8CodW2t
zwN5xljmyBvgx/Ogmo/D6+BmTwB06ATed3MR9AvvvHP0OLwb05gMDMCIP/z883u+Y55j166Ut2tXPOPB
A7m0vDTgAH15vU/3NNeGBubBU0CUoDrP18C4LZlur/mkvliu69j8JeUA3QwArsLX8/DDD++C2/nLAB7E
dEXAVqxEA6jpXr/33nu9+++/f8FHXAjkPFudB9CwHkGZgM5JAF3YPAGOcg3m/MgKPxTDQ2P0WjzaVgHs
GYDfJKLdnzp06NBRgPmKyclJji0G5kvpPIDHZXbemgCYfkydlSs/l/7ww1/Poe/iI4888jWA+t/i9v04
N76KGIL0unXrfHoXOH7IaZXLZSx3TkzEkqfuMH6CunG3g9Td7fTAE9CZWAXPPwOvxFHMm/KYC1wH8V6c
BfCDXQB0XA7QqcxlmBYuTi3DB3SP5DSwjDVA4GQSqvmlyHT7Vnm7XmIeABMCwDKwWCMA7UuwqFcA1G8H
CBmABqD5vb29BoQJ1LReuSZOkAZAmXVnWrP8gAplBHd+3W3NmjW8n6lDSvBjwB0/svL222+br6cBJE05
+qnC4iWYn8OE4FtHjhw5DTAfXATMCdZ2smU6T76en5ubCbAPPoNn68G+99cxAXkRoL4ZzzbCZ4HnIuJz
QTf4Qq0vFwFe+sGw44TnNhY6aBjDOrkQQe8hJkZkI06Q8HhhGXpI9/cPYMfABxPpdGYWc70NY2Mbp3fv
3n16586daRxzWx+j/XAu37kacIDeue/OjdxpgBoQ4LapLtO81KNMki1rlm+nTPo3FGAeAsTTsBazJ0+e
PIDjWCPkvwAQYp8AqciAOgPYCNjcl86T5IBUBpC59Qv1DagTpFmONgvAnJMBnsnOi2vrBPhaHQPmuPdJ
fB71W0ePHr0AMB9oAOYcrwBeHVhrMpGzDlOzPMt8TDBCXnC7D8Bj8OGxY0d/uHHjxjSA/W4+MyL65wDI
Eba3+fRGIHG3nBk2+0eibhSYG/QmgjMZEEcxIuN4MZ6PNChh8tKNoLzCxMTFHPgSJgmbbrvttmN79uyZ
pKV+8OBBe+y8t0sdrAEH6B388tzQnQZqGhCQtSmLRaZ5Lat1USe6rBGv+6o3bMDoPkyUNsEYFmovQPWn
2Ic+CaC+D21Zz7jgCdrci86DX4aHh81RpwAsA+y0Zmm5E6gBXvVbMk+XPa1yWue0/DWYo10GLv5fwCp/
6t13352Bm7tvenraLAGgEwKbXOxTgE4oZZKknlCRk9r1F9TBZCOAV6ELlnkaY9y7bt36YwDaezHOQUxg
puDFqADUU9AP4woA6rGVDt6Y3ZTxogleS8LAzW7EtNTpcjfADlAvwzHQWyyWPsrnZ2cymawP0B9Zv370
jWeeeYYxDAvejX4Qx3emBhygd+Z7c6N2GrA1ID/OQlkuvFAtWwpvt0nKN5JRbhLAyFibANV+gPohWNqn
Aeq/B+uUUecEpBStcQCud/r0aXOiHE+ZYyKI04oV1ztAzwA3A+cYyc51c7Q3dUAJqAHBHJH0r+7bt++v
UK+E+/YA/AloAsAaeIVvRDkMO0ldLafMThHGHfLZaK0fPnzozVWrhvd1d/fcgUj4EcSw5aampkvcs44x
05PBCY7RFToyYI7nFxAnxak5BrzJE9RrYI6PpnshAt/DMhwAAUA9lctNXsD8IA99DWAC0YcJxTH0qf8u
7LG6fAdqwAF6B740N2SngQYakB9ooawmvFAts3k7r9vYZUl5ylpKAKCI6+qwWAfgHv8l6GGsM38JYNMD
DDOgDuvVrIcTpBk4xgA4gjnamkA34jWtcO4t50dW4MY3wWWsQyDEQEL0kYG7e98LL7zwN2jn49z4LCxl
gjmTgK4AclK+kcxuE/cY/1/aJMpgYUcI8gsQzDeAcZ8vFqPnh4dvXI2xboVOJuGdmMPzpqAPrvcDtI3n
og7oeDQD5ngeY5GjO+NuJ6BDRmCvQL0A9Yi72Yr4PCvUlMlPTuYm4YUvQDPDWE+/eOLEiYvO9a5fUefz
DtA7/x26J3Aa0BoQEBbKsk/C2+3lXrrPRnWkbkMKizXAh1v6YTCehrv5Z3Cn3weX8yCAiKBL97PZngbw
McenwrI1IM7IdSaeKMePrIwj6p1ATosdoGaCywCQaYD5f+3du/d7qNoFME+jHQGSSUBXU5u383HL5P+z
rly6hi2r9wkvQYAlhe6zZ98r4/l/PDa2qRfPux3PPnP+/PlpxA8wpqAL+QpAGI9lANyAOfKg80AOjCeo
A8gJ5gEscw9gHuErMWEZsiLW0uGlKF7EVcCedtTxh++44/ZjTz/9NJcd7Hepx+/4DtKAA/QOelluqE4D
LWpA/0ALL5RdNOIXK7PLmWfS/cWShf9vVG7ArQbqfbDEzwOE98M6vQv0ZoITrFFYl/HPFC11JlrqDHg7
e/asscx5pCuBn2CO+lx79pFPod9/ffHFF/8RfD9c2AxOs8Gc3WnArYOtJZfFeqmbRNkXk91HLJ3/v7Q1
Ek4whoZWZYrF2TSC9X6yceMYgvfSdwGQ89hWlwOo01LvxvymBupxJHtsjZvFdMi5Zc3oioAOACewRwB1
A+agUZHznHQ6G0xOTl3EykY5lYqyiCnowj3fw0AavZ/5UTuuIzTgAL0jXpMbpNNA2xrQP9KNeN2prkP5
Ynlpa9cTudDFyg0Acm0ZUec9iHCfgkt8LyzXrQDhEQCUcb8TrAnsBHUCOUDKBL8RzAH+Jo8bEnjpX/YB
lP+E76//AAF2g7DcjXu/NiABXGaF19Tmk/KUNbp0v+R1kr4WyADmIT/xCuDG1rYj/7Np06Y5PMNdeAWF
CxfOG1DHc3THlrdZQ6drne52Ajf1Q0pgJ5jTIjeUeaipFOfDAoDcx7L8dKFQnMW5Ooh6j4bWrt08cerU
UZx2e8n71mN0fIdowAF6h7woN0yngSVoQIOp5tmVzmveLmslzzqS7L5E3owaoOOaOoCtCx9PKcHF/t/4
lvkIQH1TDF70ovs+wZvR7JgAmK1t4mZH5+ZcduYB5t/dv3//vyO47Hr0ydPaCPQCwDIOAddmVLcRXlP2
JXnhhYpcU5YxXSKD98DI4J3oRST+/27YsGEW694AdS8PfVwcHFyBRzcH4hCksRwhYB6vl0NHNas8KqN7
gri5APaGwv1eRJsSvBVBPv9xDnV4pj6OovW43DFeGxOIS52sAQfonfz23NidBlrTgAZZzbO1zmveLkvK
U3Y5UwRgCwFqjErnATTY2rVuBaLCfwvryLwPQc+npc6T4wBIcu/6R1Yg//aBAweeB5jfgIh2WrJso5MB
zppAlyXJbZnkpZ1Qdie8UH1PKWdZw3JEtXPWEiKWoBdxAYc3btzEgLZteITZqalcDh6MXt9nwF8gFnkd
xPGcAPLYxQ7jvRQDeVQELaI919KL0CGsdOxcC8M56JleALTxusbGxiqYQPEDLnWFcsAudZ4GHKB33jtz
I3YaWKoG9A+25tlfu3kZg91O5O3SOtARzBEcl8IaLw+g+QlOleNWr7sBRLwXt3LRrS79V2CV44OhXhmH
xHzz5ZdfPlADcwZ7CYBqKu3kfo3K7HK2k7rCt7K2rtvIvYVKmdyLAYAmoA+gDvf7m4c3bRrjs24tlSpT
CGjj/vkBADQj2c1aOXRRWyuPKYYIizwCoNNCJ2W+WgP2EODuFbAqUS0U8vx4DHWE9um+O+7YegG7DThr
ulzvU57R0auogfq/iqt4T3crpwGngaurAQKG/qFuxMuodDlldr6RTNovhdZBjY0BbNxyxiNRe3G62ss4
4vUjuN+/CAs2BZBiBLxxo8OFzI+sTGPr2jdeeeWV/0PE/A34kEsjMNcAKryMVe6fRLVM2jWSSTn7baWO
3L9eX0Adk5guHJRDUF+ByPT1MzMfT8DtXsFaey+scIA0A+G4Tm6AmwBPmXGxA7gJ6gBwXsZKLyCwDlZ6
lOckAA6PQrlcLSAAr4y1dJ8eELjenZWu30YH8g7QO/CluSE7DSxBAwQXG5jbzS/htgua8H4CcgsKapkF
ZQAjc8YpQJ0H0Pwcp8rxZLXPA8MZ6MYvuqTgpn4bW9f+7LXXXnsH0e9D4FsFc7k/7yn3bYXa9SWvKfvW
fQkv9xSq2yyowwkNI/Ox/p/CGvov4KUYgaV+E5YUJgYGBrvgiqfvHGDtE7gZCGcs8nkAp4s95Lo5Qb7A
CQDAHKBewT70MA+rHaBegbXucS0dbTPZW265a2Z8/AgnS/bfhYzX0c+4Bhygf8ZfkBue08Bl1IAGDf2j
rXm5XauyZvWlLInqsUi5LSOg83vpPICmD5b6MeR/BHf8LwHkhxD89h+IZP9nHBGbw0lyAzg+lWDEPux+
pH9N7Xq6jfCa6vpJfLsy6TtpTKYMYB5h332KzzU0dMtxOCt+E1HqnMTM9PX100qnSx1gHmCNXCxyE9UO
EA8A4hHBGzQEkDMfFLBMn69USgV8eTZf26eO/erpMvwcOFGu5GPihA+5uNSpGkj6R9upz+LG7TTgNNCa
BvjvXi79edR2Zc3qS1kS5SiT5JQxSdkCHuvKmdr563kU0OWexdUPeQpyDZDSD9s3S7oN6+m88KSal3pa
ZteR/OWgIb48lzp37tzsgw8++Btww38NgP4xjsu9qb//ugEAN8DbZ1AgrfQKKVQDi5vAHsGdboLhwIdF
tGNgXBEThTz4Ei5+Fx572DOIQ6hw+xt3BHyIg3g4QXCpAzXgLPQOfGluyE4Dl0EDBBsb+Ow8b5Mk07df
rFzXFZ73Tkq2XOcjWup0Q2NrWy+s9F7wWQCUOR+91pnUJ23l0mNo1JZ1dJnktUzupctEJlTKSJNSUn9G
Bjd7iGNiu958881z2KOO3+zUmlKpnOvr68kCuAnktMJplRs3O2RwqZv1c1jkxr0OWoVlXiGQzwG0+eU1
LE108YCZSjbrVyDnUoXZFYBARAfoSW+oA2QO0DvgJbkhOg1cIQ0IiDQC5UZyDqdZWavDlfvr+lp2CS8A
ztPlsMdcPlzC9qwr9YVfCpWx6L6kf5vqOjav753UTpfrtnJ/TXlcXojnzSDg78zIyJrVwN8sgvsZ1Ia1
9ABr4Vwfj0DNennNvR7CrV5G8FuYR5Q8wDy2zGGVc2cAXO0pWPSB4QnouAcD7oItW7YEiHiXMelxOP4z
rgEH6J/xF+SG5zTwKWigEVg3kn+SIdrA0Siv5cKTNuOlXOrY40wqFxnr6nbCJ5WLTKi0tdtIebvUA5jj
M7Lr/VzubAl783OZTNco1sLnECTIpQe6z2mNY808oBUOIA9wVfKwxudQD5HtAVzuBPAMLuOah1VepIve
AHqx2Ae+WEHAYQWAHrpvpfMVdl66Ev9AO08LbsROA04D1AB/D1pdU2fdy3HJfaWvZnkpS6KUMbEfSZoX
WSMq4CvlOi98EtUym2e+kUzKpFz2tCfRel0sNwDUc4XHHnvsLgS4jfX1dVewrp7h1jXcqxbtnsKauXGr
l+Bmxzq6b9bKK5UUaMXwsMarmCRUSTEpqOLDNVUEGVaee+45Oe9e9OBoB2nAWegd9LLcUJ0GPgUNtAOK
UldAqtXh6vrt8FKXVC7eM0ku5Y2ojFXKpR/dl8hsqus043Xfcj+7r6R8vS628DFmwMfhORf7+weGYXlz
AsA18kKpFGCdnO73Kix1HvVKgKdFHlvlslZuW+XYu1/GPv8qvrwmk4n6/RzTWRqQf4CdNWo3WqcBp4Er
rQH+NiRZ65TrS+pwPHYbyljOpNvYvF2u88ILZVvhNW3GmwZt/E9AWZpIvhWq65BvJS/1WqL4cI2Hb6aX
HnroobWpVHYLXOj8lmwAa9tY42GYxnp4yCA3eN7jCHZGszurXF7n8qXOQl++79Y9mdPAldCAAOpS+hZw
S2qryzTPupJvRnWZzUs+6b4iYx25bBnz0odQkUk+iWoZeX3p9lrerI2pB9c4aRrR6FNjY7ddh4/Licud
7nSc786gt8isjWurfHY2hZPl4rVyZ5VT/csv8Qxkl5wGnAacBpI0IEAjFjWtbbplJd8u5T2S2iTJeW+p
K+WLUbaRxLaSyOsykSdRu57OJ/Ei07QZb5cxr2UcU5JswVgRGBeNj4/jXPvyad/vGoMbnVvReOobXOwE
7oD7ynnQjqHkBwe96sREtnrzzT2V3bt3u7XyBRpdHhn9R788nsg9hdOA08CV0ICA6yelHFtSH7Zc54Vv
heo65Jna/Z0TgI1bx//XMuGbUV1m80n5RjLKG10cWWXHjh2jWEMfgHVeRIAbLfMq9uwbFzui1quzs13V
TGamisNoCORyml78VO7/y0oDzuW+rF6nexingSuqAQGdpd6kWXtd1iov9TRtxrOslUs/n9SnzOZFJvUb
lVPOJOWt5HXdRjz7DEdGRkoA8j5Y4Tgohu72AtbPszjONWMOiymXp8s4iKfy7LPPEsxdWsYaaHfmuoxV
4R7NacBpoA0NJFnZrch4i6R6Wq55+Y3SVPOsy9RMFteY/7/UnZfMcwK285KY0/IkXmSatsqznly8m/A2
ZZlEorNM+GDnzp03IQKuG4FvpZkZL+juLnE7WxXfUK86q5xquzaSRKBeG0/rntJpwGngcmlAAIWg0s7V
SrvF6nD9l/cU2uj+SeWL9c3ypDpalsSLTNNWedbjxSS8UJHZVNfHoTPXT2HPudmqtnJlj9l/jgZlgDmt
dKnLPlxaxhpoNlNdxo/tHs1pwGngMmuAvyWtXry1XdeW6bzw7VBd1+aZbyfZgKjzwrdCdR2bZ74dmdSv
0yeffLIH34VPubXydl7t8qrrAH15vU/3NE4Dn6YG5PfEBuukPMdpy7VsMV7KNW2VZ712k4CttNN54YWy
DnnJJ1G7XNeRskYyXS487+nD9Z5yp71RFddmkn+A1+bTu6d2GnAauBIaEKBm38LbNKlMyxbjpVzTVnnW
W2oSkGX7xXgp15S8nZe+bHlSXtpLGZcbXHIaMBr4f8/imyQTYOduAAAAAElFTkSuQmCC
EOF
}


# +---------------------------------------------------------------------------+
# |                                    Main                                   |
# +---------------------------------------------------------------------------+

# You can use this script in library mode:
#
#   TSWS_LIBRARY=1 . "/path/to/tsws"
#   echo "Now we're cooking with gas!"
#   tsws 192.168.0.55 8080
#
# This will load all the functions but not start the server.
#
[ -n "${TSWS_LIBRARY}" ] && return 0

declare host="${1:-127.0.0.1}"
declare port="${2:-18080}"
declare filepath="${3:-data}"
tsws "${host}" "${port}" "${filepath}"
